### ISSUE TITLE
Add Ownership Transfer Detection to Attack Detector bot

### ISSUE THREAD

**Issue by ducphamle2** [forta-network/starter-kits#104]
- Example alert of DApp Node attack: https://explorer.forta.network/alert/0x47779c362258b695e73678a74571368e66dceed14a62fb950b5f221325ae4454
- Bot: https://explorer.forta.network/bot/0x7704a975c97ed444c0329cade1f85af74566d30fb6a51550529b19153a0781cb

The ownership transfer event can be really crucial to detect or prevent attacks

**Comment by 0xtaf** [comment]
fixed in https://github.com/forta-network/starter-kits/pull/278
