### ISSUE TITLE
Sentiment bot didnt trigger on Euler attack related txt msgs

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#151]
https://etherscan.io/tx/0xbb8fc2b258ef13b83f18f62e97ec24d584be822d923dc9c634f8c94b01d642e4
https://etherscan.io/tx/0xbf295a011f0088d8a5cad4b9a15d3acebe3a4b5184f20af5ec69a07384b69a2c

**Comment by mwakaba2** [comment]
@christian-forta Here's the finding for the first tx:
```bash
$ npm run tx 0xbb8fc2b258ef13b83f18f62e97ec24d584be822d923dc9c634f8c94b01d642e4

1 findings for transaction 0xbb8fc2b258ef13b83f18f62e97ec24d584be822d923dc9c634f8c94b01d642e4 {
  "name": "Neutral Text Message",
  "description": "Hi, I believe you have some DAIs to recover() from this contract 0xeBC29199C817Dc47BA12E3F86102564D640CBf99.",
  "alertId": "NEUTRAL-NEUTRAL-TEXT-MESSAGE",
  "protocol": "ethereum",
  "severity": "Low",
  "type": "Info",
  "metadata": {
    "sentiment_score": 0.7364263534545898,
    "sentiment_time_secs": 1.2070223329999994,
    "emotion_score": 0.6115671396255493,
    "emotion_time_secs": 0.05640537499999887,
    "anomaly_score": 1
  },
  "addresses": [],
  "labels": []
}
```

The second tx message was in Chinese, so the bot couldn't parse the text correctly for analysis. We probably need a separate model to analyze Chinese text. Just not sure how often this happens. Maybe we just create a separate bot for chinese text. 
```
大佬，哪怕打去黑洞也绝不要还回去啊，干死这些傻逼项目方
```

**Comment by mwakaba2** [comment]
We can potentially use this model
https://huggingface.co/IDEA-CCNL/Erlangshen-Roberta-110M-Sentiment
