### ISSUE TITLE
High drop rate in May for [Malicious Smart Contract ML V3-beta] and [Malicious Account Funding]

### ISSUE THREAD

**Issue by manola69** [forta-network/starter-kits#189]
The following bots have a high drop rate in May, in ETH and in ETH&BSC, respectively: 

1. Malicious Account Funding- https://explorer.forta.network/bot/0x2df302b07030b5ff8a17c91f36b08f9e2b1e54853094e2513f7cda734cf68a46
2. Malicious Smart Contract ML V3-beta - https://explorer.forta.network/bot/0x9aaa5cd64000e8ba4fa2718a467b90055b70815d60351914cc1cbe89fe1c404c

It owuld be great if you could take a look and consider sharding as a solution. Thank you!

**Comment by 0xtaf** [comment]
fix in https://github.com/forta-network/starter-kits/commit/d3073a1f79e2229a002ea64815cbe8c072a5c245
and https://github.com/forta-network/starter-kits/pull/250
