### ISSUE TITLE
FN: Integrate new bridge bots into attack detector

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#219]
Vasilis, since you are in the AT already, would you mind adding the new bridge bots to the AT (the existing branch is fine). You see the constants/readme need to be adjusted for this. Thank you.

**Comment by christian-forta** [comment]
Tayfun shared the bridges here: https://docs.google.com/spreadsheets/d/1ePxySU7E3OHE_K92Lhl0OckUq6vYH2Le5CN3aV7wBDI/edit#gid=0

**Comment by Vxatz** [comment]
@christian-forta , done on https://github.com/forta-network/starter-kits/pull/203/commits/43a4e5c06be37915ed46bc1c7d1fb6a6045f905d!
