### ISSUE TITLE
Label propagation issue

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#257]
@salort-forta -

I have seen in various cases where the central is not a type of scam but has the tag of SCAM-DETECTOR-SCAMMER-ASSOCIATION.

Sharing some examples:
https://explorer.forta.network/alert/0x3d04d3daf3cd32bb83b980db3d5b233d33f349a53f73d2b2aed7728da2ee3c7f
https://explorer.forta.network/alert/0x5b37f08f43fc8945e8df9904dbc1f13e1f5886279f4f2a0d6eaefcbbdf66200f

Thought in all instances the central node has to be associated with a specific type of scam.

**Comment by salort-forta** [comment]
Sometimes the tag SCAM-DETECTOR-SCAMMER-ASSOCIATION was passing some addresses, and those would be analyzed, creating a chain reaction. 
I solved it by specifying that said tag should not be analyzed.
The push is running already, once I confirm everything runs smoothly I will close the issue.
