### ISSUE TITLE
FN alert on address poisoning

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#277]
For some reason although [this](https://explorer.forta.network/alert/0x2b39723cb4ad01483aff26c931c39bfe71b54163782ba58fef2bacd29b69d1d2) alert was triggered by the address poisoning bot, it was not picked up by the scam detector.
It ended up in an effective address poisoning scam. [Here](https://metasleuth.io/report/c5b56af9d163624332bc7c81b91f7b6b).

**Comment by Ivan1905** [comment]
Would you mind checking these two other cases? I believe the address poisoning triggered but the logic implemented in the scam detector stopped it from triggering the alert.

- Case 1: Address poisoning tx [here
](https://etherscan.io/tx/0xef73c494ef3f01f312705475371838e4869f40c3e02aea7b9997be0ca0245097). tx when the target fall into the scammer [here](https://etherscan.io/tx/0x0d63b37d0eff58948ee6fb93483838f3717f4bcbbd1c7c7311a1a0fb6814c505) 

- Case 2: Address poisoning tx [here](https://etherscan.io/tx/0x64286afcc4ec836b9f56547f9c8c89c1cdcd9ddab6ce1a216f3e898b67b22168) tx when the target fall into the scammer [here](https://etherscan.io/tx/0x7c851c425a61a7c21d8c455e58c9846b63ca82fcb74e8b77968f1923e64f6287)

**Comment by christian-forta** [comment]
fixed
