### ISSUE TITLE
FN: No CEX funding alert for FixedFloat funding

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#281]
Bot id - 0xf496e3f522ec18ed9be97b815d94ef6a92215fc8e9a1a16338aee9603a5035fb
Tx -https://arbiscan.io/tx/0x1c1b97dfb47509d2d84d3ce74939bf2f6166f830d286fc041a0e897b7196c0fb

**Comment by 0xtaf** [comment]
fixed in https://github.com/forta-network/starter-kits/pull/315
