### ISSUE TITLE
FN: No alert for new account funding

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#283]
BOT ID - 0x186f424224eac9f0dc178e32d1af7be39506333783eec9463edd247dc8df8058
Tx - https://arbiscan.io/tx/0x1c1b97dfb47509d2d84d3ce74939bf2f6166f830d286fc041a0e897b7196c0fb

**Comment by christian-forta** [comment]
if it is threshold related, lets lower the threshold for L2s across the board.

**Comment by 0xtaf** [comment]
cex funding works fine for this. I also updated the block times according to chain id, to calculate a similar expiration time for all chains.

**Comment by christian-forta** [comment]
can we close this bug?

**Comment by 0xtaf** [comment]
after the pr gets approved, I'll close this bug. Vyacheslav said that he'll review it and deploy it this week

**Comment by christian-forta** [comment]
any update, @0xtaf

**Comment by 0xtaf** [comment]
Deployed in https://github.com/forta-network/starter-kits/pull/419
