### ISSUE TITLE
FN for new account funding 

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#286]
Bot id - 0x186f424224eac9f0dc178e32d1af7be39506333783eec9463edd247dc8df8058
tx - https://arbiscan.io/tx/0x4d178696640c0085699c3278d30ff6ba29534f51799e69556523335805d663a8

**Comment by 0xtaf** [comment]
the value is $8.83 and it's below than $10 threshold. should we lower the threshold?

**Comment by christian-forta** [comment]
I would suggest to lower the threshold on cheap L2s only.

**Comment by christian-forta** [comment]
can we close this @0xtaf ?

**Comment by 0xtaf** [comment]
Deployed in https://github.com/forta-network/starter-kits/pull/419
