### ISSUE TITLE
FN: No SUSPICIOUS-CONTRACT alert during attack contract deployment

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#287]
Bot id - 0x9aaa5cd64000e8ba4fa2718a467b90055b70815d60351914cc1cbe89fe1c404c
tx - https://arbiscan.io/tx/0x864c8cfb8c54d3439613e6bd0d81a5ea2c5d0ad25c9af11afd190e5ea4dcfc1f

**Comment by christian-forta** [comment]
Was identified as safe contract:
https://explorer.forta.network/alert/0xa33912a1ebd1582dcff9b4a8aa2643786d83c9ecaaef4ae0053c5092934a48eb

{"address_contained_in_created_contract_1":"0xd614927AcFB9744441180c2525faf4cEdB70207f","address_contained_in_created_contract_2":"0xBA12222222228d8Ba445958a75a0704d566BF2C8","address_contained_in_created_contract_3":"0x8DB0eFEE6A7622CD9F46A2CF1aEdC8505341A1a7","address_contained_in_created_contract_4":"0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8","address_contained_in_created_contract_5":"0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1","address_contained_in_created_contract_6":"0x82aF49447D8a07e3bd95BD0d56f35241523fBab1","address_contained_in_created_contract_7":"0x912CE59144191C1204E64559FE8253a0e49E6548","address_contained_in_created_contract_8":"0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9","address_contained_in_created_contract_9":"0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f","anomaly_score":"0.5524781341107872","model_score":"0.0","model_threshold":"0.5","oko_contract_explorer":"https://oko.palkeo.com/0x2c53CA7DA834aC1650db9FAF1179513eb0f7574e/"}

**Comment by christian-forta** [comment]
@salort-forta , can you see why the model produced a low score on this contract in terms of feature weights?

**Comment by salort-forta** [comment]
The contract has very short code, just a handful of opcodes. And most of them were processed as 'UNKNOWN', therefore the model didn't have any information on combinations of opcodes to determine that it was an attacker, and thus marked it as non-attacker

**Comment by christian-forta** [comment]
Interesting. Is it a proxy contract?

**Comment by salort-forta** [comment]
I'm not sure. the code, processed looks like this:
![image](https://github.com/forta-network/starter-kits/assets/126703476/99a5e2da-56f2-4714-884a-6a8e9f6d36b5)

**Comment by christian-forta** [comment]
Nested contract creation; lets test the smart contract ML bot after the trace fix from Oct 10th. Christian to test.

**Comment by christian-forta** [comment]
So @salort-forta , reviewing the bot, it actually operates on the entire initialization code, not the smart contract code itself. As such, when you run your investigation, dont get the contract code, but rather the initialization code from the input data field of the tx. Could you pls run that on this particular FN and see what happens. 

Can you also confirm that the training is actually done on the initialization code as opposed to the smart contract code?

**Comment by salort-forta** [comment]
Running it on every one of the contracts created based on this view:
https://arbiscan.io/tx/0x864c8cfb8c54d3439613e6bd0d81a5ea2c5d0ad25c9af11afd190e5ea4dcfc1f#internal

Tx:			0x864c8cfb8c54d3439613e6bd0d81a5ea2c5d0ad25c9af11afd190e5ea4dcfc1f
Chain:			arbitrum
From:			0x2c53ca7da834ac1650db9faf1179513eb0f7574e
Contract address:	0x3C236C919B4174B3123C1DA298A30Ff7e70D03d2
![image](https://github.com/forta-network/starter-kits/assets/126703476/6fcf8830-156c-4390-8df4-2df574be495a)


Tx:			0x864c8cfb8c54d3439613e6bd0d81a5ea2c5d0ad25c9af11afd190e5ea4dcfc1f
Chain:			arbitrum
From:			0x3C236C919B4174B3123C1DA298A30Ff7e70D03d2
Contract address:	0x0930c3ACa019D2f311dD4b2aD2eeDe5BB1933661
![image](https://github.com/forta-network/starter-kits/assets/126703476/7eb988f2-45bc-4dfc-bbfa-6cc04e04631b)

Tx:			0x864c8cfb8c54d3439613e6bd0d81a5ea2c5d0ad25c9af11afd190e5ea4dcfc1f
Chain:			arbitrum
From:			0x8db0efee6a7622cd9f46a2cf1aedc8505341a1a7
Contract address:	0x1270E7694d38f3f80e0E033703c1272A80B914Fc
![image](https://github.com/forta-network/starter-kits/assets/126703476/71a8e4bb-a169-4f06-abe6-97d182020df4)

Tx:			0x864c8cfb8c54d3439613e6bd0d81a5ea2c5d0ad25c9af11afd190e5ea4dcfc1f
Chain:			arbitrum
From:			0x8db0efee6a7622cd9f46a2cf1aedc8505341a1a7
Contract address:	0x9Ea522292ed9e3CC345bac4FBdBc199E638f8Ad0
![image](https://github.com/forta-network/starter-kits/assets/126703476/be8320a3-ebc4-4400-bb0a-fb1d26435bf2)


All of them are marked as non-malicious

**Comment by Thisisgeorg3** [comment]
@salort-forta any updates here?

**Comment by salort-forta** [comment]
New version of the model in beta detected this (score = 0.5311 > 0.53 = threshold)
