### ISSUE TITLE
FN: No UNVERIFIED-CONTRACT-CREATION alert 

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#288]
bot id - 0x4c7e56a9a753e29ca92bd57dd593bdab0c03e762bdd04e2bc578cb82b842c1f3
tx - https://arbiscan.io/tx/0x864c8cfb8c54d3439613e6bd0d81a5ea2c5d0ad25c9af11afd190e5ea4dcfc1f

**Comment by 0xtaf** [comment]
![image](https://github.com/forta-network/starter-kits/assets/25147738/1b2a2c46-668d-400a-980c-e0323c03febe)

creates a successful finding locally. there must be something wrong with the node at the moment
