### ISSUE TITLE
FN: No FLD_Laundering alert 

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#293]
BOT ID - 0x186f424224eac9f0dc178e32d1af7be39506333783eec9463edd247dc8df8058
Tx - https://arbiscan.io/tx/0xcccbc71047cde695a48da2e0c73fdd0a3ade20a0428779cc0bb9c099c3f2fb5a

**Comment by 0xtaf** [comment]
![image](https://github.com/forta-network/starter-kits/assets/25147738/50249bef-23d3-47fe-9798-94877375021e)
blocks in memory was too short to capture the Stargate Router. the value was increased, so it will catch now
