### ISSUE TITLE
FN: No ASSET-DRAINED alert

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#294]
BOT ID - 0xe4a8660b5d79c0c64ac6bfd3b9871b77c98eaaa464aa555c00635e9d8b33f77f
Txs - 
https://arbiscan.io/tx/0x79c05da7c382635f1fbfd09f44946b6284b3defdcec2fdd2ab29fda1e197d142
https://arbiscan.io/tx/0x8c556d37970eb026780fbd3a6f3960cb891684fac627bb71585febbabc6d4c88
https://arbiscan.io/tx/0x32eaa0b1463fd8b10b449a7f96d29ebe0c384d2c0624edab93d5aa0861100fbe

**Comment by 0xtaf** [comment]
seems like a trace rpc issue
