### ISSUE TITLE
FN: No Reentrancy alert for tx

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#298]
BOT ID - 0x492c05269cbefe3a1686b999912db1fb5a39ce2e4578ac3951b0542440f435d9
Tx - https://optimistic.etherscan.io/tx/0x3d6367de5c191204b44b8a5cf975f257472087a9aadc59b5d744ffdef33a520e

**Comment by Thisisgeorg3** [comment]
Plz reassign if necessary @Vxatz

**Comment by Vxatz** [comment]
@Thisisgeorg3 , the issue is that Reentrancy Detector can't work on chains where traces are not supported.
