### ISSUE TITLE
FN: No LARGE-TRANSFER-OUT alert 

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#299]
BOT ID - 0xaf9ac4c204eabdd39e9b00f91c8383dc01ef1783e010763cad05cc39e82643bb
Tx - 
https://optimistic.etherscan.io/tx/0x27f0fd9584f1307a1e7aee8671276681b7e5a093a4bdfecf79af2fbe948b8a31
 (Opt bridge)
https://optimistic.etherscan.io/tx/0xf02b85e3e7816cfafa556664fdb8793f23fce2fa1686431d77116e83113c1f9e

**Comment by 0xtaf** [comment]
hmm I haven't seen any Optimism alerts during that period, let alone these 2. 
we should keep that in mind an monitor after enabling the bot again 👍

**Comment by christian-forta** [comment]
@0xtaf ?

**Comment by 0xtaf** [comment]
@christian-forta sorry I forgot to reply this one. locally the both txns works fine as expected

![image](https://github.com/forta-network/starter-kits/assets/25147738/f4b3c768-8d27-45fc-873b-c1354a1c8f44)
![image](https://github.com/forta-network/starter-kits/assets/25147738/0dd5c398-13c7-4340-abec-41130cb0b9bd)

**Comment by christian-forta** [comment]
Let's close the issue then
