### ISSUE TITLE
FN: No FLD_NEW_FUNDING alert for new account funding

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#300]
BOT ID - 0x186f424224eac9f0dc178e32d1af7be39506333783eec9463edd247dc8df8058
Funding Tx -
https://bscscan.com/tx/0xe4cdfc5e491b07b13a61239ba52326bea7095770e50663413031be09ff5ba43c

**Comment by 0xtaf** [comment]
the problem about not receiving txns from the networks is fixed. 
However, since this tx was triggered by "WithdrawETH" function, it wasn't caught by the bot. 

this event will also be added

**Comment by christian-forta** [comment]
yes pls. thanks Tayfun.

**Comment by 0xtaf** [comment]
Christian, `WithdrawETH` only includes value. in order to fetch the receiver we need traces. for BSC I think we can't do it? should I close this?

**Comment by christian-forta** [comment]
has the fix been deployed yet? could you pls close the bug once deployed?

**Comment by 0xtaf** [comment]
I'll close it as soon as it's deployed.

**Comment by christian-forta** [comment]
Is it deployed yet? @0xtaf ?

**Comment by 0xtaf** [comment]
Deployed in https://github.com/forta-network/starter-kits/pull/419
