### ISSUE TITLE
FN: No UNVERIFIED-CODE-CONTRACT alert for attack contract

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#302]
BOT ID - 0x4c7e56a9a753e29ca92bd57dd593bdab0c03e762bdd04e2bc578cb82b842c1f3
Tx - https://bscscan.com/tx/0xce0e119a317a9e67f37f67e281c546b2cf7df3d4f37e4a660faf245461d49134

**Comment by christian-forta** [comment]
Unable to repro:

1 findings for transaction 0xce0e119a317a9e67f37f67e281c546b2cf7df3d4f37e4a660faf245461d49134 {
  "name": "Contract with unverified code was created",
  "description": "0x4b44b52ef15f7aab9a0a6cfdfa8d2c5eeeb6d8c3 created contract 0x1c651B04bDd1C1718EEeafedE0A3c13e87024fa2",
  "alertId": "UNVERIFIED-CODE-CONTRACT-CREATION",
  "protocol": "ethereum",
  "severity": "Medium",
  "type": "Suspicious",
  "metadata": {
    "address_contained_in_created_contract_1": "0x55d398326f99059fF775485246999027B3197955",
    "address_contained_in_created_contract_2": "0x657334B4FF7bDC4143941B1F94301f37659c6281",
    "address_contained_in_created_contract_3": "0x2120F8F305347b6aA5E5dBB347230a8234EB3379",
    "anomaly_score": 0.0006720430107526882
  },
  "addresses": [],
  "labels": [
    {
      "entityType": "Address",
      "entity": "0x4b44b52ef15f7aab9a0a6cfdfa8d2c5eeeb6d8c3",
      "label": "attacker",
      "confidence": 0.3,
      "remove": false,
      "metadata": {}
    },
    {
      "entityType": "Address",
      "entity": "0x1c651B04bDd1C1718EEeafedE0A3c13e87024fa2",
      "label": "attacker_contract",
      "confidence": 0.3,
      "remove": false,
      "metadata": {}
    }
  ],
  "uniqueKey": "",
  "source": {}
}

**Comment by christian-forta** [comment]
Bot health in terms of dropped tx looks OK. I suspect, the etherscan API ran out of quota, but we now have a paid endpoint, which should mitigate this issue.
