### ISSUE TITLE
No LAUNDERING-TORNADO-CASH alert for tornado cash laundering 

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#305]
BOT ID - 0x4adff9a0ed29396d51ef3b16297070347aab25575f04a4e2bd62ec43ca4508d2
tx - https://bscscan.com/tx/0x55b84471d9a52f90e9ae4579844581286a2b67f85869ee44449aa5e882289a63
https://bscscan.com/tx/0x3ca50ae3792b14f91cc71256f7d9d496725783215fba2888ac7a60e371f4a553

**Comment by 0xtaf** [comment]
all these txns together with https://github.com/forta-network/starter-kits/issues/306 happened in the same hours and even almost same minutes. so I suspect that there was something odd in the network at that time. this is indeed an FN but I can reproduce locally. I'll consider a possible drop as well. thanks 👍
