### ISSUE TITLE
HIGH-BORROW-VALUE bot is disabled

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#308]
Bot Id - 0x2c8452ff81b4fa918a8df4441ead5fedd1d4302d7e43226f79cb812ea4962ece

**Comment by christian-forta** [comment]
@Ivan1905 , I think this was a victim of the purge; can you pls stake it and get enabled again?

**Comment by christian-forta** [comment]
@Ivan1905 , can we restake this?
