### ISSUE TITLE
FP on label association

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#313]
I have seen a couple of cases when the central node has been flagged as ice-phisher, that the label association flags the victim.

1. [This](https://explorer.forta.network/alert/0xb011e3e5d0f3fce404279a99c5a8ef148f8e770b9a952396c48fe5ed993f65f6) case 0x85a6a6c7210d19c3be0097db764ad86705307b84 stole their assets.
2. [This](https://explorer.forta.network/alert/0x357bbe2a5e33bbe0411e844db52fa1c5b1876f6ca0089589dbf14f79725930ae) case 0x962c15268b4cbea0382f42c5ba901ce46528b629 stole their assets.

**Comment by christian-forta** [comment]
@salort-forta any update on this one?

**Comment by christian-forta** [comment]
deactivate global model for ice phishing [easy, fast, less coverage]

**Comment by salort-forta** [comment]
Added branch covering this. Testing locally, once I have a hit for ice-phishing I will deploy to the network and pr

**Comment by salort-forta** [comment]
Updated it in the network. I'll wait for a day to ensure everything is running smoothly and I'll close it tomorrow
