### ISSUE TITLE
Scam Detector MM alerts to voluminous

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#319]
Seems like caching isnt working.

**Comment by Vxatz** [comment]
Opened PR https://github.com/forta-network/starter-kits/pull/314 (Also adding error alerts)

**Comment by Vxatz** [comment]
Closed PR, and pushed to `ScamDetector_MM_NIP` branch: https://github.com/forta-network/starter-kits/commit/74e12dba4d4773bf33a119c9e1cceed9a3db21d9

**Comment by christian-forta** [comment]
fixed
