### ISSUE TITLE
Scammer association - FN issue

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#323]
Hi there,

I have observed, when pulling the alerts for the label propagation, that it only alerts when the central node has been flagged by the ice-phishing label. Would you mind taking a look? thanks!!

**Comment by salort-forta** [comment]
I found alerts where the central node is not ice-phishing
https://explorer.forta.network/alert/0x260543c51cc71609c9da87025a934919a8b3dd1e62a6fb97c42bc89d4de00e36

**Comment by Ivan1905** [comment]
Okay, it's weird because from the week 10/2 - 10/8 there weren't any but considering you found one, let's close this one!
