### ISSUE TITLE
Attack Detector not taking into account tornado cash funding alerts

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#324]
This is causing alerts to be emitted later than they should. Example alerts are:

https://explorer.forta.network/alert/0xf209db67186cd819434ee5de908b2d4505f993d8680db102c6f2a093cc0df513
https://explorer.forta.network/alert/0x6bd8b21946aebe3861a90ab75e013eb6e13a7f34e1b95b83c1c20a9333123f94
https://explorer.forta.network/alert/0x66434b093987a673d8901130350f7d761c6cc9d47706a1bc132087f2ea7ce166

Seems like funding alert should have a longer expiry time in the dynamo DB to mitigate.

**Comment by Vxatz** [comment]
Fixed in https://github.com/forta-network/starter-kits/pull/450
