### ISSUE TITLE
No UNVERIFIED-CODE  alert for unverified contracts creation

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#329]
BOT ID - 0x4c7e56a9a753e29ca92bd57dd593bdab0c03e762bdd04e2bc578cb82b842c1f3

Txs 
1) https://etherscan.io/tx/0xbc863c288a5eaa6bd0bcc411b546828a2b89deb786063b45aaf32ba280a21501

2) https://bscscan.com/tx/0xb76f72341c4cac8ecf8b6a7cfd38cfea6ad48ede0d7a5d891ab62e5fc3a14b4e

**Comment by christian-forta** [comment]
need to double check after the fix and close this issue

**Comment by christian-forta** [comment]
verified: 
{
  "name": "Contract with unverified code was created",
  "description": "0x4453aed57c23a50d887a42ad0cd14ff1b819c750 created contract 0x6cE5a85CFF4c70591DA82De5eb91c3Fa38B40595",
  "alertId": "UNVERIFIED-CODE-CONTRACT-CREATION",
  "protocol": "ethereum",
  "severity": "Medium",
  "type": "Suspicious",
  "metadata": {
    "address_contained_in_created_contract_1": "0x164AFe96912099543BC2c48bb9358a095Db8e784",
    "address_contained_in_created_contract_2": "0xb1Cc59Fc717b8D4783D41F952725177298B5619d",
    "address_contained_in_created_contract_3": "0xB386c1d831eED803F5e8F274A59C91c4C22EEAc0",
    "address_contained_in_created_contract_4": "0x759c6De5bcA9ADE8A1a2719a31553c4B7DE02539",
    "address_contained_in_created_contract_5": "0xf59257E961883636290411c11ec5Ae622d19455e",
    "anomaly_score": 0.0005030181086519115
  },
  "addresses": [],
  "labels": [
    {
      "entityType": "Address",
      "entity": "0x4453aed57c23a50d887a42ad0cd14ff1b819c750",
      "label": "attacker",
      "confidence": 0.3,
      "remove": false,
      "metadata": {}
    },
    {
      "entityType": "Address",
      "entity": "0x6cE5a85CFF4c70591DA82De5eb91c3Fa38B40595",
      "label": "attacker_contract",
      "confidence": 0.3,
      "remove": false,
      "metadata": {}
    }
  ],
  "uniqueKey": "",
  "source": {}
} for first tx
