### ISSUE TITLE
 No FUNDING-TORNADO-CASH alert for TC funding 

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#331]
BOT ID - 0xa91a31df513afff32b9d85a2c2b7e786fdd681b3cdd8d93d6074943ba31ae400
Tx - https://bscscan.com/tx/0x2a3366501b7412cb92e2eba4ae91fd5e74dd4c7ebb93b0007593f416982013ce

**Comment by 0xtaf** [comment]
there's actually no problem in the code. it must be node related 

![image](https://github.com/forta-network/starter-kits/assets/25147738/f1caac07-cea0-4620-8062-06232c7801d2)

**Comment by christian-forta** [comment]
this issue is that we have two TC funding alerts. A small amount is considered evidence of an impeeding attack whereas a large amount is more for indicators of privacy usage. As such, the alert is not utilized in the AD.
