### ISSUE TITLE
No CEX funding alert for mexc funding. 

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#332]
BOT ID - 0xf496e3f522ec18ed9be97b815d94ef6a92215fc8e9a1a16338aee9603a5035fb

Tx - https://etherscan.io/tx/0x4c571705dcd4538d6caac5bd7a351ba8e2dbfc565ef3d0226b7f6d0d040ac5f2

**Comment by 0xtaf** [comment]
fixed in https://github.com/forta-network/starter-kits/pull/339
