### ISSUE TITLE
AD didn't trigger with enough base alerts

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#335]
The following alerts exist for 0x44Af5FcedFb77a2d9Cb973B404e30FC27e666708 but no AD alert

https://explorer.forta.network/alert/0x5f45c647b0b2234d87f00fe42ccaaae0e920d7fefe000e249f818fc723b0264a
https://explorer.forta.network/alert/0x1d97c5de690a4da9bc463246b0b76d88fbbfc7a77f92ea3eacaeb5964e06942a
https://explorer.forta.network/alert/0xcebec014a0514710f3784deb7dd1ed175b9611fa8eafe742ea14230ed22d0b12
https://explorer.forta.network/alert/0x5d4699458b22ef500d3aa082ab8090d9577410b88aaf556690569d50c93632e7

**Comment by christian-forta** [comment]
based on these alerts, should the AD have triggered based on the current logic?

**Comment by Thisisgeorg3** [comment]
Need to investigate performance. 
Is it an AD issue or Network issue, assigning to Rodri.
