### ISSUE TITLE
unclear information in FP mitigation alert

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#340]
Vasilis, its unclear on why this was marked as an FP:
https://explorer.forta.network/alert/0x489666c3f8f52a2435219f4ea6ab0f571535d659791e233a022c3f94fc4c250a

Querying the address directly results in:
[{'address': 'XXX',
  'nametag': 'Fake_Phishing185653',
  'internal_nametag': '',
  'url': '',
  'shortdescription': '',
  'notes_1': 'There are reports that this address was used in a Phishing scam. Please exercise caution when interacting with it.',
  'notes_2': '',
  'labels': ['Phish [/](https://file+.vscode-resource.vscode-cdn.net/) Hack'],
  'labels_slug': ['phish-hack'],
  'reputation': 2,
  'other_attributes': [],
  'lastupdatedtimestamp': 1690948848}]
  
  I think it would be good to include information about the label in the metadata of the FP-ETHERSCAN alert.

**Comment by Vxatz** [comment]
PR Fixing the bug and adding label info in metadata: https://github.com/forta-network/starter-kits/pull/342/

**Comment by christian-forta** [comment]
fix already deployed
