### ISSUE TITLE
FN on multicall

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#341]
Vasilis, 

https://etherscan.io/tx/0x4329c267d03999dc8f9f2f879a9e969381d926fddd802e4eadab8133780fe3c1

if we see multicall tx to a known scammer contract (0x00000E58D0901615A382043fb5059732c0270000), we would want to have an ice phishing alert on this that extracts additional scammer information. 

In this particular case, the user signed a permit message off-chain, which then is utilized by the attacker to issue this transaction on-chain. 

What we are missing is the extraction of the addresses to which the permit is being made to (0x53... and 0x46...). This is desirable, because it would open the door to protect users against signing that off-chain message (as one of the addresses need to be a parameter to the permit function and therefore is visible within the user's wallet)

**Comment by Vxatz** [comment]
@christian-forta, the permission is given to the scammer contract itself, as it's the one calling the ERC20's `transferFrom`. Would exposing the recipients (0x53... and 0x46...) still add value?

**Comment by Vxatz** [comment]
Added in https://github.com/NethermindEth/Forta-Agents/pull/456.

**Comment by christian-forta** [comment]
fix already deployed
