### ISSUE TITLE
FP address poisoner

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#343]
Hi there,

There's an FP case where the address poisoning bot is flagging bulk transfers of NFTs:

1. [Alert](https://explorer.forta.network/alert/0x4875173a896ae81ec1c03218c87819eb4da71ee7d8485a7b8276a9f350b3d79e)
2. [Alert](https://explorer.forta.network/alert/0x97980186fbdf8f54f11780c2c86b440ac0f49bd0a7b00a58424d8e3822e2cbe5)
3. [Alert](https://explorer.forta.network/alert/0x08f85a7594c6a294ed1a58c62cd71b1ae854031106b241012fa1748d0b83ab19)

**Comment by Vxatz** [comment]
Fix on PR https://github.com/forta-network/starter-kits/pull/346
