### ISSUE TITLE
Quality issue on scammer association alert

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#349]
bot_id=0x1d646c4045189991fdfd24a66b192a294158b839a6ec121d740474bdacb3ab23
alert ids:
0xc7abdc08c5bd584c9fd7fa8dc4456b869de8808b2787155bae7f4340a608db56
0x404b7867ea4ddb34bf1efa10a4d00a671dc87a9da99752b9cf810bc615b84d7e
0x53e2f27ae8127a60dc56be8ed74b7cb42c9482b1002fc2caf5cf87c8bfd7a6f7
We have a SCAM-DETECTOR-SCAMMER-ASSOCIATION with an empty associated_scammer_threat_categories (edited)

**Comment by christian-forta** [comment]
seems like these alert IDs are no longer in the system; looking at october SCAMMER-ASSOCIATION data, I dont see any empty associated scammer threat categories labels.

**Comment by christian-forta** [comment]
https://explorer.forta.network/alert/0x083b42b6dcba7a2cfb2aa5c5c9281b8d517a9b6eed915162820e4a31595d9cf9

is based on manual alerts; for those the threat category isnt handled correctly.

**Comment by christian-forta** [comment]
for the others its related to FP issues. Should not be running scammer association on those alerts: https://github.com/forta-network/starter-kits/issues/350

**Comment by mjraha592** [comment]
I am a blind and deaf person who has the ability to see and hear. Until today, my daughter was doing my work. She also got married and left. My request to you is to activate the smart robot in my laptop so that my work can be completed without leaving it as a goal. Thank you.

**Comment by christian-forta** [comment]
fixed

**Comment by mjraha592** [comment]
لطفا مسدود وجلوگیری شود از روند خودمختار
