### ISSUE TITLE
Anomalous Token Transfer ML Bot Improvement: Separate Model Service

### ISSUE THREAD

**Issue by mwakaba2** [forta-network/starter-kits#35]
A machine learning model currently lives in the bot container where the model data processing and bot logic is coupled. 
There's an option to query a custom endpoint with a scan node signed JWT that the endpoint will check. 
It may make sense to create a separate service hosting the model that a bot can access via an endpoint. The service will have resources specifically tailored to the model's needs, store secrets securely, and can make supporting features such as online-training easier. In a bot container, data doesn't persist through restarts and re-deployments, so any stateful executions will be challenging (e.g. saving retrained model, versions, training data).

**Comment by christian-forta** [comment]
@mwakaba2 is this still topical?
