### ISSUE TITLE
Scammer Association is propagating on false positive entries

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#350]
https://explorer.forta.network/alert/0xb624e1fa3a4b9e2250e1a4456c3815e4cd2b12212545e1fd79c690b0e288fa8b

pls make sure those type of alerts are not raised.

**Comment by salort-forta** [comment]
Added branch with solution, will deploy now and will monitor, if it works will close it

**Comment by mjraha592** [comment]
I am a blind and deaf person who has the ability to see and hear. Until today, my daughter was doing my work. She also got married and left. My request to you is to activate the smart robot in my laptop so that my work can be completed without leaving it as a goal. Thank you.
