### ISSUE TITLE
FP issue - social engineering

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#352]
Hi there!

For this week we have seen an increase in number of alerts for the social engineering label. After investigation, seems that this label has been mixing up with native ice phishing. 
E.g:

1. This [alert](https://explorer.forta.network/alert/0x8074c0104ad20c27675938a48b9f10b9f6e443e4fea8977964822c69fdbef32d) does not have a source alert. Also, the flagged address only seems to be linked with native ice phishing as it received native token txs.
2. This [alert](https://explorer.forta.network/alert/0xcec603a07c2a36fb27de7cec9b360d361743054cb3e6249d58b74463e66c781e) - The same than case 1.

**Comment by Vxatz** [comment]
Hi @Ivan1905, NIP-7 was linked to social engineering in the SD. I changed it to point to native ice phishing this commit https://github.com/forta-network/starter-kits/commit/54a5c43c253f335991113c7629dee36884d5444b.

cc @christian-forta

**Comment by Vxatz** [comment]
(I have now also updated the comment next to it)
