### ISSUE TITLE
FP on funding alert

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#354]
https://explorer.forta.network/alert/0x82903ccf3e95b7b88b53751c754caabe29e49a08afd4b8860b36ced2ea263ddc triggered, but the user wasnt new and previously funded

**Comment by christian-forta** [comment]
secrets.json already has those keys; can you deploy the bot and close this bug?

**Comment by christian-forta** [comment]
has this been deployed yet? Can we close this issue, @0xtaf ?

**Comment by 0xtaf** [comment]
Deployed in https://github.com/forta-network/starter-kits/pull/419
