### ISSUE TITLE
FP on funding alert

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#355]
https://explorer.forta.network/alert/0xb19c4e273fde4ec8136f5c9ca405deec475e3d33b14fd206824833d532e2c5ed

**Comment by 0xtaf** [comment]
what's the context here? [internal tx](https://etherscan.io/address/0xb0a1d2f84b5c6cdbc00f2dadc8a53bae67d1cdde#internaltx) shows a funding 🤔

**Comment by christian-forta** [comment]
The account is old and was funded over 4 months ago; why do we see a new funding alert

**Comment by 0xtaf** [comment]
addressed the bug in the pr. will close once deployed

**Comment by christian-forta** [comment]
has this been deployed yet, @0xtaf ?

**Comment by 0xtaf** [comment]
@christian-forta it's merged but not deployed yet. I'm waiting a response from Vyacheslav

**Comment by 0xtaf** [comment]
Deployed in https://github.com/forta-network/starter-kits/pull/419
