### ISSUE TITLE
Fork fraudulent NFT and scam notifier bot

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#357]
https://app.forta.network/bot/0x112eaa6e9d705efb187be0073596e1d149a887a88660bd5491eece44742e738e
https://app.forta.network/bot/0x513ea736ece122e1859c1c5a895fb767a8a932b757441eff0cadefa6b8d180ac

**Comment by christian-forta** [comment]
scam notifier is forked
fraud nft trader to be forked tomorrow if we dont hear from david

**Comment by Vxatz** [comment]
Scam Notifier deployed: `0xdd83ac89fbc5dd028b7c4a711d4f0c5b13412b171801b126cb5f79b916920cd2`
Manually added notifiers:
1) https://etherscan.io/address/0xba6e11347856c79797af6b2eac93a8145746b4f9
2) https://etherscan.io/address/0x666a3ce3f9438dccd4a885ba5b565f3035984793

**Comment by christian-forta** [comment]
Vasilis actively working on this

**Comment by Vxatz** [comment]
Fixed both bots.
