### ISSUE TITLE
FP issue - ice phishing

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#371]
Seems to be an issue when 1inch auction happens.

E.g:
[Here](https://app.forta.network/alerts/0x6a3947be260b9bc95fe37e15a798eee253e4ce7fedec7db86d9e00e56d4113d1)

[Here](https://app.forta.network/alerts/0x432088a7507ddea61963b22aaac1a4d7f188de1c3b16fbd086afef1a882be1d4)

Both addresses are invoking the 1inch contract. Considering the liquidity is not coming from a LP but rather from another address seems it is the auction mode of 1inch.

**Comment by christian-forta** [comment]
Ivo pls follow up whether the fix was deployed and close this

**Comment by christian-forta** [comment]
no longer observing the issue
