### ISSUE TITLE
SD FP Mitigation Idea

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#373]
Codify the USDC deposit heuristic and/or the amount of USDC received heuristic (Rodri will add details here) in a SD FP mitigation.

@rodri-forta - could you pls add details to this item.

**Comment by rodri-forta** [comment]
The heuristic consisted of watching the last 1 year of transactions and checking the amount and the frequency of the transactions. Is unlikely to see high volume and frequent transactions on USDC, also considering summing the total amount received and compare it to the rest of the scammers, if % of the total volume was high it was very unlikely it was a Scammer.
