### ISSUE TITLE
FN for CEX-FUNDING bot

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#378]
BOT ID - 0xf496e3f522ec18ed9be97b815d94ef6a92215fc8e9a1a16338aee9603a5035fb
Funding Tx  - 
https://etherscan.io/tx/0x7b3a3aec76f0e2e4b8d9880fc5973e44c8c31b3f3e581abfdece22ddef9efa0b  (exch funding)
https://snowtrace.io/tx/0x18018972c4631e510f3b4af7a6cf2149ae37f64d17ff1c183caf9fd2d85a6d09  (fixed float)

**Comment by 0xtaf** [comment]
fixed in https://github.com/forta-network/starter-kits/pull/394
