### ISSUE TITLE
FN for FLD Laundering bot

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#379]
BOT ID - 0x186f424224eac9f0dc178e32d1af7be39506333783eec9463edd247dc8df8058
Tx  
https://etherscan.io/tx/0x7d498153be4c9abbd62ba7d165fe7fd10ca68333b4bf27b04ac747d7ebd1b725 (railgun laundering)

**Comment by 0xtaf** [comment]
fixed in https://github.com/forta-network/starter-kits/pull/434
