### ISSUE TITLE
FN for FLD funding bot

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#380]
BOT ID - 0x186f424224eac9f0dc178e32d1af7be39506333783eec9463edd247dc8df8058
Tx -
 https://etherscan.io/tx/0xb053c139737c6f6c3cb466a8ca97ff0d6c39eac2bd43ade8a5698133f909ee76 (railgun)
https://snowtrace.io/tx/0x18018972c4631e510f3b4af7a6cf2149ae37f64d17ff1c183caf9fd2d85a6d09 (FixedFloat)
https://etherscan.io/tx/0x7b3a3aec76f0e2e4b8d9880fc5973e44c8c31b3f3e581abfdece22ddef9efa0b (exch)
https://etherscan.io/tx/0x7fe97cce4d626f9baaa0edb5ea712df237dbf2972cfe25d952b8257a9a79b785 (Avalanche bridge)

**Comment by christian-forta** [comment]
in progress

**Comment by 0xtaf** [comment]
fixed a bug and updated some block number values at https://github.com/forta-network/starter-kits/pull/434, https://github.com/forta-network/starter-kits/pull/419 and
avalanche bridge and exch txns will be caught after this update https://github.com/forta-network/starter-kits/pull/394
