### ISSUE TITLE
FN for UNVERIFIED-CODE bot

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#382]
BOT ID - 0x4c7e56a9a753e29ca92bd57dd593bdab0c03e762bdd04e2bc578cb82b842c1f3
 Tx - 
 https://snowtrace.io/tx/0x4f37ffecdad598f53b8d5a2d9df98e3c00fbda4328585eb9947a412b5fe17ac5
 https://snowtrace.io/tx/0x9d402deee6956f6227c9993458d883a4a98e1093142ba74221fe0f175474e3f9
https://snowtrace.io/tx/0xab5f6242fb073af1bb3cd6e891bc93d247e748a69e599a3744ff070447acb20f
https://snowtrace.io/tx/0x4425f757715e23d392cda666bc0492d9e5d5848ff89851a1821eab5ed12bb867

**Comment by 0xtaf** [comment]
![image](https://github.com/forta-network/starter-kits/assets/25147738/a6fe8361-fadd-4ce2-ae99-e047c930378b)
![image](https://github.com/forta-network/starter-kits/assets/25147738/cc38a45d-f843-4e8e-8119-eda9dcc4b38b)

these were already fixed and will be caught in the future transactions
