### ISSUE TITLE
FN for Reentrancy bot

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#384]
BOT ID - 0x492c05269cbefe3a1686b999912db1fb5a39ce2e4578ac3951b0542440f435d9
Tx - 
https://snowtrace.io/tx/0x4f37ffecdad598f53b8d5a2d9df98e3c00fbda4328585eb9947a412b5fe17ac5

**Comment by Vxatz** [comment]
Reentrancy bot can unfortunately work only on Ethereum and Fantom, as it requires traces.

**Comment by christian-forta** [comment]
lets see whether we can bring our on RPC endpoint once the platform feature is ready to expand trace coverage to other chains.
