### ISSUE TITLE
FN for ASSET-DRAINED bot 

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#385]
BOT ID - 0xe4a8660b5d79c0c64ac6bfd3b9871b77c98eaaa464aa555c00635e9d8b33f77f
Tx -
https://snowtrace.io/tx/0x4f37ffecdad598f53b8d5a2d9df98e3c00fbda4328585eb9947a412b5fe17ac5
https://bscscan.com/tx/0x24a2fbb27d433d91372525954f0d7d1af7509547b9ada29cc6c078e732c6d075

**Comment by RCantu92** [comment]
The draining of assets for the BSC txn is a 97% decrease, rather than >99% that the bot uses.
