### ISSUE TITLE
FN for LARGE-PROFIT bot

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#386]
BOT ID - 0x7cfeb792e705a82e984194e1e8d0e9ac3aa48ad8f6530d3017b1e2114d3519ac
Tx - 
https://snowtrace.io/tx/0x4f37ffecdad598f53b8d5a2d9df98e3c00fbda4328585eb9947a412b5fe17ac5
https://snowtrace.io/tx/0xab5f6242fb073af1bb3cd6e891bc93d247e748a69e599a3744ff070447acb20f
https://snowtrace.io/tx/0x4425f757715e23d392cda666bc0492d9e5d5848ff89851a1821eab5ed12bb867
https://bscscan.com/tx/0x24a2fbb27d433d91372525954f0d7d1af7509547b9ada29cc6c078e732c6d075

**Comment by Vxatz** [comment]
Opened PR https://github.com/NethermindEth/Forta-Agents/pull/464.
