### ISSUE TITLE
FN - Address poisoning

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#388]
[This](https://etherscan.io/address/0xb087269de7ba93d0db2e12ff164d60f0b3675870#tokentxns) address seem to have executed a 1.4M address poisoning. The address poisoning bot haven't flagged it.

**Comment by Vxatz** [comment]
Missed because the attacker used these symbols "𝐔𝐒𝐃𝐂, 𝐔𝐒𝐃𝐓, 𝐃𝐀𝐈" for "USDC, USDT, DAI" which were not monitored.
Will include them in the next update.

**Comment by Ivan1905** [comment]
Thanks!!!
