### ISSUE TITLE
AD FN: ChangeNow bot maintenance

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#395]
Could you pls move the code into our repo and redeploy the bot (Trevor is transferring the bot ownership). 
Also, seems like changenow does support Arb/Op/ and Avalanche. Could you pls add support for those. 

The OP address is https://optimistic.etherscan.io/address/0x0a1ce4496471867fac0ad71b785e5258993c9b33.
For Arb/Avalance you may need to transfer some ETH to find out which is the address.

**Comment by christian-forta** [comment]
Heard from trevor; he will transfer next week; @0xtaf , would be great if you could start working on the new detection logic already.

**Comment by christian-forta** [comment]
Christian to do the PR

**Comment by christian-forta** [comment]
bot is already deployed

**Comment by 0xtaf** [comment]
fixed in https://github.com/forta-network/starter-kits/pull/406 & https://github.com/forta-network/starter-kits/pull/410
