### ISSUE TITLE
FP - NFT washtrade

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#403]
For some reason there are cases where the basebot of the scam detector alert is not linked with alert id.

- [Here](https://app.forta.network/alerts/0xb45ea221956ccdc80ab4e124a9d9efcf714691fc7038cec1085b38697318656e) - The base bot drives to a poisoning alert.
- [Here](https://app.forta.network/alerts/0x416706e20b2c552e253bf4f784ba1ba38a576e80baa943766bc7dd6b3574973a) - The base bot drives to a poisoning alert.

**Comment by Thisisgeorg3** [comment]
I'll take this assignment

**Comment by Thisisgeorg3** [comment]
resolved.
