### ISSUE TITLE
FN - Ice phishing

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#405]
Regarding [this](https://etherscan.io/tx/0x7204f9c50c5ddd8734bba6279fb68333170b8e651ae4ffd7c4e8ed87cd142564) the ice phishing bot seem to have detected the address that the victim interacted, [here](https://app.forta.network/alerts/0x92badb169a799b06c6c1582946539c8eec91710159f1df1a2ef671626cc8239a) the alert.

However, I don't see the alert coming from the scam detector.

**Comment by Vxatz** [comment]
There was a bug in the way NIP-9's metadata were parsed, which has been fixed.
