### ISSUE TITLE
FN: AD Blocksec alerts need to be decrypted

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#408]
The blocksec alerts are now encrypted; need to decrypt them (see SD for how to do so)

**Comment by Vxatz** [comment]
@christian-forta, base branch should be `AD_3_52_MEV_Consensus`, correct?

**Comment by christian-forta** [comment]
yep; 3_52_MEV_Consensus

**Comment by christian-forta** [comment]
deployed with 3.52.4 on beta2
