### ISSUE TITLE
FP - ice phishing

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#409]
I'm seeing a lot of FPs casually on addresses that have traded a token called Mind.

- [This](https://etherscan.io/address/0x9615b377876cfba6fdcd7792e8832b77dca4e758) address was labeled in [this](https://app.forta.network/alerts/0x07761daa6e431f4b35d881caae59b023fc924d1748e5cda06c169c19964b1ac8) alert

- [This](https://etherscan.io/address/0xED6A768fb6e7f10079e1b5a465BA7eA6920A8726) address was labeled in [this](https://app.forta.network/alerts/0xa9ef45762bc5c6d2c3d35cc5078ce4d83fbfbb04feafa86b01de8b44efb6f412) alert

- [This](https://etherscan.io/address/0x8303c2c242b74ff038435424fe2d19c2b6ad2e9f) address was labeled in [this](https://app.forta.network/alerts/0xbb9971fae1f0f7fa4b1a71bd770187fcc70f941f4be3d20f142c996f0bb89a29) alert

**Comment by Vxatz** [comment]
The token was falsely alerted as suspicious by the "Malicious Smart Contract ML V2" bot, the alerts of which are consumed by the Ice Phishing bot.

I added a check of the number of different transaction initiators (calling the "suspicious" contract). If the number is high, we consider the contract safe and don't raise an alert.

**Comment by Vxatz** [comment]
We have now removed the specific alert from the Scam Detector.
