### ISSUE TITLE
FP - Address poisoning

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#413]
Apparently there is an FP coming from the null address on polygon. Alert [here](https://app.forta.network/alerts/0x0edef087d3fe64d3fa7f8c7a0f3647e1934251a57b2702fa65eeb4e3b90b2997)

I measured the address poisoning label on monday and had a 100% so this sounds strange to me (note: the measurement was done on mainnet so maybe there's an issue on polygon?)

**Comment by Vxatz** [comment]
Thanks @Ivan1905. The issue here seems to be that most of the attackers addresses had a higher transaction count than the victims, and that caused the FP. (The attackers also had a non-zero MATIC balance, so that check also wouldn't help).

I'll look into a possible fix.

**Comment by christian-forta** [comment]
maybe age could be used to determine who is victim/attacker
