### ISSUE TITLE
FN - nft trader not alerting on ethereum?

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#414]
Example tx: 

https://etherscan.io/tx/0xc0980b6a2944a13a8d5797b09d91598fe6f64d1bb319b00cae9209dc805fa5b4

**Comment by Vxatz** [comment]
Bot redeployed. ID: 0x15e9b3cd277d3be1fcfd5e23d61b3496026d8c3d9c98ef47a48e37b3c216ab9f
