### ISSUE TITLE
Permit and dynamically created contracts

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#415]
https://explorer.phalcon.xyz/tx/eth/0xbe936387c03605abea7c4994b83befe57f38cbd00cae2d378611a4de403e7b62

Here a contract is created on the fly, which the user given permission to though an off-chain signature. 

From a protection perspective, the contract needs to be in FF threat intel prior to this tx. 

This can only be done by proactively generating contract addresses based on the EOA and nonce into the future.

**Comment by christian-forta** [comment]
One way to address is to create contract labels into the future from within the scam detector. How many needs to be evaluated looking on-chain. 

For instance: 0x00003ffa7857408ab714c28b1451914330240000 produced 144 contracts in the last day:

SELECT DISTINCT to_address FROM ethereum_mainnet.traces
JOIN (SELECT hash FROM ethereum_mainnet.transactions WHERE from_address = '0x00003ffa7857408ab714c28b1451914330240000' and data_creation_date > DATE('2023-12-01')) as tx
ON tx.hash = ethereum_mainnet.traces.transaction_hash
WHERE data_creation_date > DATE('2023-12-01')
and trace_type = 'create'

**Comment by christian-forta** [comment]
Scammer deployed contract function in scam detector could be expanded to:
1. look at trace information to see whether contract is created
2. if it is, calculate the contract information out for at least 5 txs

**Comment by Vxatz** [comment]
Fixed in https://github.com/forta-network/starter-kits/pull/433.

**Comment by Thisisgeorg3** [comment]
Deployed today. Closing issue.

**Comment by Ivan1905** [comment]
I wanted to confirm this is effectively working.

- Yesterday there was [this](https://phalcon.blocksec.com/explorer/tx/eth/0x93a0ce0711edaf7664c26b3654095f1052010bb7da62c135b6ef0c425c0c2f09?line=6) $4M phishing scam.
- I believe the permitted contract was [this](https://etherscan.io/address/0x226539793536bcee7f8992d0ff67bb37905be0a1) one but the SD was not able to catch.

**Comment by Thisisgeorg3** [comment]
@Vxatz please take a look when you have moment at this. Not a priority, just want to confirm @Ivan1905 finding. 
thank you for handling it

**Comment by Vxatz** [comment]
Apologies for the delay, this has now been fixed 👍
