### ISSUE TITLE
FP ice phishing

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#422]
This could be linked with https://github.com/forta-network/starter-kits/issues/409

The scam detector is pointing out:

- This [alert](https://app.forta.network/alerts/0xbda29758a13198ac57184e4b57634ce509ecaa33dca0a9fb9b082ec7d4ffec74) and the tx linked seems to be [a nromal swap](https://etherscan.io/tx/0xc1bdeb2ced89fdd1d4ffc8f1f0044acdf9e3f19ad5d67887946a304a2cb1b180) 

- [Here](https://app.forta.network/alerts/0x5e69ae2bf3e9062a0f5cfd89e2ec7c7dc338ff69a606d88d800c819fbc77926b) another example and the tx [here](https://etherscan.io/tx/0x27dce5032b2a9d8e9587af9b3182f981827b3decdbed99c83c98d077862d5fb6)

**Comment by Vxatz** [comment]
Similarly to https://github.com/forta-network/starter-kits/issues/409, the token was falsely alerted as suspicious by the "Malicious Smart Contract ML V2" bot,

The number of unique tx initators check (see comment on the other issue) wouldn't work in this case, as the "suspicious" contract was self-destructed and so the number of initiators returned is 0.

In the future, we could consider adding an Etherscan label check for the suspicious contract (The etherscan pro endpoint is required in this case)

**Comment by Thisisgeorg3** [comment]
Not a priority at the moment

**Comment by Vxatz** [comment]
Closing this, as the specific alert has been removed from the Scam Detector.
