### ISSUE TITLE
FN for Malicious-smart-contract-ml-v3 bot

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#423]
Txs - 
https://etherscan.io/tx/0xf24b09aa8bcdf2c40db17ee9ca9254d7cff384a19ee440f4edecf3eef615c4a9
https://etherscan.io/tx/0xfa35a2d5d91ee31be5027a071b916bc6fd48a72d62ad91358cf77c4870ea17db
https://snowtrace.io/tx/0xc6888665eb748df000dfbc49c81577270a7cced1454d7e5feb135dd536630a87?chainId=43114
https://arbiscan.io/tx/0x31c882550bd89d777363e6c057a24c3c364d397394333fd28f44b18bd085c120
https://etherscan.io/tx/0x002ccdb4a53a760cb03984db3e8e91325c4f732458d0f21603f64ebb536e4e6e
https://bscscan.com/tx/0x00be1efadf619bfca09059a25b76af3cd1413608074372c594856705612c2e3b

Bot Id  - 0x9aaa5cd64000e8ba4fa2718a467b90055b70815d60351914cc1cbe89fe1c404c

**Comment by salort-forta** [comment]
- score = 0.5446 > 0.5 = threshold [beta]
- score = 0.5454 > 0.5 = threshold [beta]
-
- score = 0.5607 >  0.53 = threshold [beta]
- score = 0.5027 > 0.5 = threshold [beta]
- score = 0.527 < 0.53 = threshold [beta]. But this address triggered a lot in the scam detector
