### ISSUE TITLE
FN for Flashloan Detection Bot

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#424]
Txs - 
https://arbiscan.io/tx/0x51293c1155a1d33d8fc9389721362044c3a67e0ac732b3a6ec7661d47b03df9f 
https://etherscan.io/tx/0xbf5b2d22fa88965ddfc6e6d685fc7cfc683340c49e126386759ed9e4027b1415
https://etherscan.io/tx/0xb3456a338d7b3e7936a4d08b34e265818c116b7871baef8df1492a35f9f3b1bc
https://etherscan.io/tx/0x09a3a12d58b0bb80e33e3fb8e282728551dc430c65d1e520fe0009ec519d75e8
https://etherscan.io/tx/0x485e08dc2b6a4b3aeadcb89c3d18a37666dc7d9424961a2091d6b3696792f0f3
https://etherscan.io/tx/0x396a83df7361519416a6dc960d394e689dd0f158095cbc6a6c387640716f5475
https://arbiscan.io/tx/0x27f13eaa3d72dbd32bda5d758e0ecbd689f6d23f60ec7b0c27a4042a6c68fa20
https://arbiscan.io/tx/0xe98ba64e06c3e8d2385abac92814b52ea0105510e19a94c9a004a2cdd548281a
https://bscscan.com/tx/0x0be817b6a522a111e06293435c233dab6576d7437d0e148b45efcf7ab8a10de0
https://etherscan.io/tx/0xfeedbf51b4e2338e38171f6e19501327294ab1907ab44cfd2d7e7336c975ace7

Bot ID - 0x55636f5577694c83b84b0687eb77863850c50bd9f6072686c8463a0cbc5566e0

**Comment by RCantu92** [comment]
Ethereum mainnet txn [0xbf5b2d22fa88965ddfc6e6d685fc7cfc683340c49e126386759ed9e4027b1415](https://etherscan.io/tx/0xbf5b2d22fa88965ddfc6e6d685fc7cfc683340c49e126386759ed9e4027b1415) was missed because the bot didn't properly handle `Deposit`s into the WETH contract. Logic has been updated.

However, the txn wouldn't have been alerted because the profit is too low of a percentage of the borrowed amount and wouldn't exceed the threshold.

**Comment by RCantu92** [comment]
Ethereum mainnet txn [0xb3456a338d7b3e7936a4d08b34e265818c116b7871baef8df1492a35f9f3b1bc](https://etherscan.io/tx/0xb3456a338d7b3e7936a4d08b34e265818c116b7871baef8df1492a35f9f3b1bc) had an alerted generated locally without code changes. Thus issue is not logic-side. Increasing sharding for bot on Ethereum mainnet.

**Comment by RCantu92** [comment]
Ethereum mainnet txn 0x485e08dc2b6a4b3aeadcb89c3d18a37666dc7d9424961a2091d6b3696792f0f3](https://etherscan.io/tx/0x485e08dc2b6a4b3aeadcb89c3d18a37666dc7d9424961a2091d6b3696792f0f3) was missed for the same reason as the above comment. Fix would address previous and this comment.

**Comment by RCantu92** [comment]
Ethereum mainnet txn [0x396a83df7361519416a6dc960d394e689dd0f158095cbc6a6c387640716f5475](https://etherscan.io/tx/0x396a83df7361519416a6dc960d394e689dd0f158095cbc6a6c387640716f5475) was missed for the same reasons as the two previous txns/comments.

**Comment by RCantu92** [comment]
Ethereum mainnet txn [0xfeedbf51b4e2338e38171f6e19501327294ab1907ab44cfd2d7e7336c975ace7](https://etherscan.io/tx/0xfeedbf51b4e2338e38171f6e19501327294ab1907ab44cfd2d7e7336c975ace7) was missed for the same reasons as the _three_ previous txns/comments.

Additionally, the sDAI token on Ethereum mainnet, [0x83F20F44975D03b1b09e64809B757c47f942BEeA](https://etherscan.io/address/0x83f20f44975d03b1b09e64809b757c47f942beea), doesn't emit a `Transfer` alert when tokens are burned. Thus it was attributing an additional 2M USD in profit to the txn initiator that it shouldn't have. Bot logic has been updated for this "peculiar" token.

**Comment by RCantu92** [comment]
Arbitrum txn [0x51293c1155a1d33d8fc9389721362044c3a67e0ac732b3a6ec7661d47b03df9f](https://arbiscan.io/tx/0x51293c1155a1d33d8fc9389721362044c3a67e0ac732b3a6ec7661d47b03df9f) requires an endpoint with tracing, which we do not have.

**Comment by RCantu92** [comment]
Arbitrum txn [0x27f13eaa3d72dbd32bda5d758e0ecbd689f6d23f60ec7b0c27a4042a6c68fa20](https://arbiscan.io/tx/0x27f13eaa3d72dbd32bda5d758e0ecbd689f6d23f60ec7b0c27a4042a6c68fa20), according to [Phalcon](https://phalcon.blocksec.com/explorer/tx/arbitrum/0x27f13eaa3d72dbd32bda5d758e0ecbd689f6d23f60ec7b0c27a4042a6c68fa20), ends with the txn initiator profiting ~0.933 ETH after withdrawing from the Arbitrum WETH contract. However, to continue investigating to confirm the end result, we would need an Arbitrum endpoint with tracing, which we currently do not have.

**Comment by RCantu92** [comment]
Arbitrum txn [https://arbiscan.io/tx/0xe98ba64e06c3e8d2385abac92814b52ea0105510e19a94c9a004a2cdd548281a](https://arbiscan.io/tx/0xe98ba64e06c3e8d2385abac92814b52ea0105510e19a94c9a004a2cdd548281a) suffers from the same problem as the Arbitrum txn above.

**Comment by RCantu92** [comment]
The BSC txn [0x0be817b6a522a111e06293435c233dab6576d7437d0e148b45efcf7ab8a10de0](https://bscscan.com/tx/0x0be817b6a522a111e06293435c233dab6576d7437d0e148b45efcf7ab8a10de0) was properly processed by the bot logic. The reason it did not create an alert was because the profit did not exceed the profit threshold (profit was ~56K USD; threshold was 100K USD). Additionally, the profit/borrowed percentage was also under the necessary threshold (percentage was 1.9%; threshold was 2%).

**Comment by Thisisgeorg3** [comment]
Thanks for handling this @RCantu92

**Comment by Vxatz** [comment]
Fixed in https://github.com/NethermindEth/forta-starter-kits/pull/96.
