### ISSUE TITLE
FN for funding-tornado-cash bot

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#425]
Tx - https://etherscan.io/tx/0x9c9cbdd4c71a5633b118eee3f75eaedebb3a72fa816dbd1a9b264805c1b1f165
BOT ID - 0xa91a31df513afff32b9d85a2c2b7e786fdd681b3cdd8d93d6074943ba31ae400

**Comment by 0xtaf** [comment]
this wasn't a new account. that's why it wouldn't emit a finding

**Comment by christian-forta** [comment]
pls check whether this ever triggered on this account

**Comment by 0xtaf** [comment]
it wasn't triggered earlier probably due to a dropped tx issue
