### ISSUE TITLE
FN for unverified-contract-creation bot

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#426]
Txs - 
https://etherscan.io/tx/0xfa35a2d5d91ee31be5027a071b916bc6fd48a72d62ad91358cf77c4870ea17db
https://snowtrace.io/tx/0xc6888665eb748df000dfbc49c81577270a7cced1454d7e5feb135dd536630a87?chainId=43114
https://etherscan.io/tx/0x002ccdb4a53a760cb03984db3e8e91325c4f732458d0f21603f64ebb536e4e6e
https://arbiscan.io/tx/0x31c882550bd89d777363e6c057a24c3c364d397394333fd28f44b18bd085c120

BOT ID - 0x4c7e56a9a753e29ca92bd57dd593bdab0c03e762bdd04e2bc578cb82b842c1f3

**Comment by 0xtaf** [comment]
fixed in https://github.com/forta-network/starter-kits/pull/435
