### ISSUE TITLE
No FLD_Laundering alert for laundering txs

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#428]
Txs - 
https://arbiscan.io/tx/0x6ec1bb6db0fc29e888d1b58fadd945e1c76c8930176f194e7ec58abb9530c610
https://arbiscan.io/tx/0x6d65a0240ffcd6947c35cb560b57a4f8927b14a117bac62b45b9529b2fd5fbfa
https://snowtrace.io/tx/0x0fcceaf33ad3c43ee88fa9c553a65eae01e574c578cae8b0d541029578cf0be2?chainId=43114

BOT ID - 0x186f424224eac9f0dc178e32d1af7be39506333783eec9463edd247dc8df8058

**Comment by 0xtaf** [comment]
addresses in https://github.com/forta-network/starter-kits/pull/434

**Comment by Thisisgeorg3** [comment]
need to close
