### ISSUE TITLE
FN for CEX Funding bot

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#429]
Tx - https://etherscan.io/tx/0x66ca81f63da96c0406cc028b5809f26bbbc3263382c0c6415512c0bdc0fa8eb9 (OKX funding)
BOT ID - 0xf496e3f522ec18ed9be97b815d94ef6a92215fc8e9a1a16338aee9603a5035fb

**Comment by 0xtaf** [comment]
tx is 100 days old. OKX address was added 2 weeks ago only. it should work the next time.
![image](https://github.com/forta-network/starter-kits/assets/25147738/c197b8c9-6d26-4349-a4a5-d4e3f91fbd02)
