### ISSUE TITLE
FN for large-profit-bot 

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#431]
Txs - 
https://etherscan.io/tx/0x09a3a12d58b0bb80e33e3fb8e282728551dc430c65d1e520fe0009ec519d75e8/advanced
https://etherscan.io/tx/0x485e08dc2b6a4b3aeadcb89c3d18a37666dc7d9424961a2091d6b3696792f0f3
https://etherscan.io/tx/0x396a83df7361519416a6dc960d394e689dd0f158095cbc6a6c387640716f5475
https://arbiscan.io/tx/0x27f13eaa3d72dbd32bda5d758e0ecbd689f6d23f60ec7b0c27a4042a6c68fa20
https://arbiscan.io/tx/0xe98ba64e06c3e8d2385abac92814b52ea0105510e19a94c9a004a2cdd548281a
https://bscscan.com/tx/0x0be817b6a522a111e06293435c233dab6576d7437d0e148b45efcf7ab8a10de0
BOT ID - 0x7cfeb792e705a82e984194e1e8d0e9ac3aa48ad8f6530d3017b1e2114d3519ac

**Comment by Vxatz** [comment]
Opened PR https://github.com/NethermindEth/Forta-Agents/pull/464.
