### ISSUE TITLE
Issue calculating contract nonce

### ISSUE THREAD

**Issue by Vxatz** [forta-network/starter-kits#440]
In these cases https://github.com/search?q=repo%3Aforta-network%2Fstarter-kits%20%22else%201%22&type=code, the nonce is set to 1 when a contract is deployed by another contract. While this is correct for the first contract deployed by each contract, the nonce gets incremented in subsequent creations. 
To calculate the correct nonce, web3 library can be used (note that contract nonces begin with 1, so we need the nonce - 1 in order to calculate the new contract addresses correctly)

**Comment by Thisisgeorg3** [comment]
Contract address not properly cal. leads to FN 
P1
