### ISSUE TITLE
FPs attack detector coming from the funding-laundering-detector

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#449]
We believe that the AD is flagging some FPs due to some alerts coming from the funding-laundering-detector in the funding/money laundering stage.

These base bots alerts aren't FPs, what should be reassessed is if these sources should be considered as something suspicious.

e.g: [Here](https://app.forta.network/alerts?addresses=0x31ef83a530fde1b38ee9a18093a333d8bbbc40d5&agents=0x80ed808b586aeebe9cdd4088ea4dea0a8e322909c0e4493c993e060e89c09ed1&limit=15&sort=desc) many cases where the bot triggered as GMX was considered as suspicious

[Here](https://app.forta.network/alerts?addresses=0xEBf4FBB9C81b84dd5CF89BC75588E5d0018501b3&agents=0x80ed808b586aeebe9cdd4088ea4dea0a8e322909c0e4493c993e060e89c09ed1&limit=15&sort=desc) when binance hot wallet was considered as suspicious

**Comment by Vxatz** [comment]
FLD alerts have now been removed from the Attack Detector.
