### ISSUE TITLE
FP for SIMILAR SCAM CONTRACT DETECTED

### ISSUE THREAD

**Issue by rileyg98** [forta-network/starter-kits#454]
https://app.forta.network/alerts/0x820925281dc28f4213d3ca7d800139a8945423e8d83637219b724c08e124b1e5 Detected creation of a Openzeppelin upgradeable proxy as a scam contract similar to a proxy used in a scam. Given this is template code, I'd call this a FP. 

Also flagged as https://app.forta.network/alerts/0xbee1b20356760e6c04703002729380b0aa98258b6ae39cc9f410c6a6a4235c64 for the same contract deployment.

**Comment by Ivan1905** [comment]
Adding it to the FP list as well

**Comment by Thisisgeorg3** [comment]
@Ivan1905 can i close?
