### ISSUE TITLE
FN on CEX funding - Fixed float

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#458]
Opening this issue in order to flag [this](https://bscscan.com/tx/0x996b4c44315f72cc8d11e927cde071ea3e7b0289e64c8aa6a4acfa4c41e9e4f9) tx which was not flagged by the Cex funding bot. Address was funded by fixed float and then deployed the malicious smart contract.
The funding tx was run against the CEX bot locally and there were 0 findings. I am assuming here that something in the logic of the bot is not working properly.

**Comment by Ivan1905** [comment]
Adding this one as well.
https://etherscan.io/tx/0xddc95468ee754d7ad062c353ff7ae2d0fecaae35b2dac0fe22b370b3fb49a078
which the cex funding bot did not alert

**Comment by Thisisgeorg3** [comment]
Fixedfloat bot created - to be deployed to beta alt

**Comment by Vxatz** [comment]
Deployed to prod.
