### ISSUE TITLE
FN on changenow bot

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#459]
In this opportunity [this](https://app.forta.network/bot/0x9324d7865e1bcb933c19825be8482e995af75c9aeab7547631db4d2cd3522e0e) bot was not able to catch [this](https://etherscan.io/tx/0x1e1815d709817b6a591319b2a9de8822d6e1c3f72a50e8c0f672fb6e495bd5f4) changenow funding. Attacker then deployed the malicious smart contract and attacked. Run the changenow bot locally and it did not emit any findings.

**Comment by Vxatz** [comment]
Closing this, as the FN was due to performance and there has been an performance update in this [PR](https://github.com/forta-network/starter-kits/pull/437)
