### ISSUE TITLE
FN TC funding 

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#460]
In this case the TC funding bot did not flag [this](https://etherscan.io/tx/0x9c9cbdd4c71a5633b118eee3f75eaedebb3a72fa816dbd1a9b264805c1b1f165) tx. The bot was run locally with zero across the mentioned tx with zero findings.

**Comment by Thisisgeorg3** [comment]
Discussed today, there were multiple tornado cash funding txns. 

Adding Harrison to this. No need to do anything at the moment unless this becomes a more frequent issue.
