### ISSUE TITLE
FN Union chain

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#461]
Is it possible to add coverage for union chain? From what I saw on their website, the addresses that are using are shown there. https://unionchain.ai/

We had misses in these two txs:

- [Radiant](https://etherscan.io/tx/0x8b3ac1b28e817b8bb2d284cb64516604e8f39bfe778f2e74949f498cef9ee9c6) 
- [This](https://etherscan.io/tx/0x0de408884ebd33844728c667f04baae645a2dc9a6878da89ba92444433ce55b8) one as well.

Union chain was reported to be used by SC attacker and rug pullers.

**Comment by Thisisgeorg3** [comment]
Bot is complete - to be deployed to beta alt

**Comment by Vxatz** [comment]
Deployed to prod.
