### ISSUE TITLE
Potential FPs due to clustering

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#463]
We have some cases where the attack detector alerted in the execution phase although having a funding alert and a malicious contract creation alert. For these cases at least one hop was executed by the attacker. The goal of this issue is to investigate if clustering is not working properly

e.g1:

 **Onix attack**
- Attacker used [this](https://etherscan.io/address/0x43083e943cd4d35f242f7850be2402126a57d6b5#internaltx) address to fund vía TC. We have [alerts](https://app.forta.network/alerts?addresses=0x43083E943cd4D35F242F7850bE2402126A57D6B5&agents=0xa91a31df513afff32b9d85a2c2b7e786fdd681b3cdd8d93d6074943ba31ae400&limit=15&sort=desc) for TC funding.
- Attacker executed two hops and ended in [this](https://etherscan.io/address/0x085bdff2c522e8637d4154039db8746bb8642bff) address (the one that eventually deployed the malicious smart contract)
- The ml bot flagged the contract [here](https://app.forta.network/alerts/0x54f2227348c062c122b2189ff8237b1e14bc920b711e17618b690ed6246cf7ba)
- The attack detector did not include in the metadata the funding base bot alert. Alert [here](https://app.forta.network/alerts/0xb6bf6d79a547c1a3695c872504b552cc7b520a397442d30a95549012058ae324)

e.g2:

**LinkDAO**
- Attacker used [this](https://bscscan.com/address/0xb4616fc8e355a37b15ea81af86653be74e35b9fb#internaltx) address to fund vía TC. We have an alert [here](https://app.forta.network/alerts/0x096d70513d3c3dc93d891db6bb858d3d131117b1e3880c06e99a16c8b9fe68b5)
- Attacker executed one hop and ended in [this](https://bscscan.com/address/0xdf6b0200b4e1bc4a310f33df95a9087cc2c79038) (the one that eventually deployed the malicious smart contract)
- The ml bot flagged the contract [here](https://app.forta.network/alerts/0x072ae632daa3defee0772a4be19f5cfeb5fdc8aed17c3d5cd3e92da1f6608a96)
- The attack detector did not include in the metadata the funding base bot alert. Alert [here](https://app.forta.network/alerts/0xae9cf51addff52d534d73cf29db2f475a8f7af1cc56ed20e09a660c1f3a0fc92)

**Comment by Thisisgeorg3** [comment]
@Vxatz plz let me know if you have too many P0's on your plate.

**Comment by Vxatz** [comment]
In both cases, there had been an issue with the Entity Clustering bot, which has been fixed since its last update.
