### ISSUE TITLE
FN - multichain

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#473]
I see that there was not any alert for the multichain hack, not even in the beta one.

Attacker: 0x1D7E1Aa3D3057566D436EBBa9225C01f9A60a00d
Network: Avalanche
I see [a suspicious contract creation](https://app.forta.network/alerts/0x3bd918aec87157ede8c3139c4a5d681ea818f76109befcf7851db989ebd4ec88) also a explotation alert [large profit](https://app.forta.network/alerts/0x4e9bffbb3a76dc1d3833bc8ef76782cc388561c464d6245999262f3d08e51f3a), I guess the AD should have triggered with these two.

**Comment by Thisisgeorg3** [comment]
@Ivan1905 - plz check if the AD picked this up. 

These findings are not related to the AD bot.

**Comment by Ivan1905** [comment]
@Vxatz this attacker was funded by https://debridge.finance/ which is a cross chain bridge. It is the same issue than the one mentioned here https://github.com/forta-network/starter-kits/issues/504
