### ISSUE TITLE
FP-luno Smart contract wallet[AD]

### ISSUE THREAD

**Issue by 0xbhagi** [forta-network/starter-kits#476]
- [alert](https://app.forta.network/alerts/0xe9366d8f3932084cbf905b8227781d7607264954fd82185dc5dc3d16c8b21c0a)
- [0x2E05A304d3040f1399c8C20D2a9F659AE7521058](https://etherscan.io/address/0x2e05a304d3040f1399c8c20d2a9f659ae7521058)

**Comment by Thisisgeorg3** [comment]
Harrison

**Comment by Thisisgeorg3** [comment]
Asset drained base bot, lower priority

**Comment by 0xhowen** [comment]
Seems to be working as intended? If > threshold then alert will execute in this case. Someone generated a wallet and within the same block withdrew all the assets for some reason. Causing an alert. 

Potentially mitigated by a list of known wallet, cex.

**Comment by Thisisgeorg3** [comment]
Thanks @0xhowen 

Added to FP list 
https://github.com/forta-network/starter-kits/blob/main/scam-detector-py/fp_list.csv
