### ISSUE TITLE
FN - Hexacoin attack

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#479]
[Here](https://etherscan.io/address/0x1aD4c765d73635Ac8beDD09f1e18c5d1e0905549) the address of the attacker

There is a [malicious smart contract](https://app.forta.network/alerts/0x1813a3e54ee1505f22933e6e43b043700f08518ff99f9af2ee2240deb7eb6926) and [a TC funding](https://app.forta.network/alerts/0xe06f8329f0b49aa843e709ccdba549e2ee0e4a0d14f1529e07cbdcef9eb2dec5) but not an AD alert.

**Comment by Thisisgeorg3** [comment]
Please investigate nature of this issue

**Comment by Vxatz** [comment]
The issue was the expiration of the funding stage alert. I have increased that time from 1 day to 10 days, but here the interval is 21 days.

Please let me know if I should further increase it.

**Comment by Thisisgeorg3** [comment]
@salort-forta lowered this to 1 day in the lean AD. 

I would leave it at 10 days and see which direction we go in with the changes coming to AD. 

Thanks for this, closing.
