### ISSUE TITLE
Basket DAO - FN

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#480]
- [Here](https://etherscan.io/address/0x63136677355840F26c0695dD6DE5C9E4f514f8e8) the attacker
- There was a post mortem [alert](https://app.forta.network/alerts/0x3250688723f5dcc54251e58381fc7a6c7a39f053291c4880ee09a7bbf31429ef) on the beta version
- There was [an alert](https://app.forta.network/alerts/0xaf94b2ddf65ce114ccf628436b5344793a8715883ac02c58094f3f2514fd4d5e) for large profit and [suspicious contract creation](https://app.forta.network/alerts/0x8aaa29f0a729554f1cb553dc83733fce0a3823c05a2cd2c74213a7965a7f2c83)
- There were 3 hops and a gap of day between funding an SC deployment

**Comment by Thisisgeorg3** [comment]
Investigate nature of this failure

If network related, place on backlog

**Comment by Vxatz** [comment]
@Ivan1905, considering that 1) We now have a Fixed Float funding bot, 2) The Entity Clustering bot works correctly, 3) The attacker deployed the malicious contract shortly after they received the funds, I believe we will be able to catch similar scenarios in the future.

**Comment by Thisisgeorg3** [comment]
Great! Closing.
