### ISSUE TITLE
FP for large profit bot

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#485]
https://app.forta.network/alerts/0xd5929e90f7c1489585c69b60ddd9bc6536b1c2278e3ede73d2c21271a7932283 (borrow tx)
https://app.forta.network/alerts/0x291dcd53206533e988b82697d1aa31d07b9af4d9d7f65fc6bf99bf1c170824b9 (The tx initiator didn't get any profit/fee from the tx)
https://app.forta.network/alerts/0x8c00fe3751b7dd61e7c495461323dc3bfb40b6895575c74a3ef807437e7ac1e3 (tx initiator didn't get any profit) 
https://app.forta.network/alerts/0x3e82a9616282db9db14567eaaa1375c5e9f7f82ae3501d2c1a1edd2060064015 (uniswap tx)
https://app.forta.network/alerts/0x6a14ec900e3116062d32cc4a9910698f88f5cfb1c8a19bd61f0fb5e12f708062 (uniswap tx)

**Comment by Vxatz** [comment]
For the 2nd, I'm now filtering out batch transfers of the same token

**Comment by Vxatz** [comment]
Fix has been deployed
