### ISSUE TITLE
FP for Reentrancy bot

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#486]
https://app.forta.network/alerts/0x6c56b16274259a4aed8441c92cca56e236845f7a23252857ae98f326d9aa4cd6 (uniswap increase liquidity tx)
https://app.forta.network/alerts/0xce12967d6cdf1d91fef2b871e8b159f063a7dc212e9d824485ba066c7bf28ead

**Comment by Thisisgeorg3** [comment]
Reentrancy - not a priority atm

**Comment by Vxatz** [comment]
Created a PR https://github.com/NethermindEth/Forta-Agents/pull/467/commits/46712290a80b162ddc21ba43c34f365c84924352

Filters out transactions with high tx count contracts called at the top-level
