### ISSUE TITLE
FP for FLD_NEW_FUNDING bot

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#487]
https://app.forta.network/alerts/0xba76b6570c8309147552be7f5df2220abd51078556bd715d80289a7948b3029f (binance funding, cexes with proper kyc shouldn't be alerted on)
https://app.forta.network/alerts/0x81d1587e6b7d2788499204d45cf45beb53697790991ffb640260694480433d57 (uniswap tx)

**Comment by Ivan1905** [comment]
Closing this one considering the mentioned bot is no longer part of the AD

**Comment by Ivan1905** [comment]
Closing this one considering the mentioned bot is no longer part of the AD
