### ISSUE TITLE
large profit bot - FP

### ISSUE THREAD

**Issue by 0xbhagi** [forta-network/starter-kits#501]
- Attacker: [0x916584c1a4debd37b3390b659a4a63ef7aa9f7df](https://etherscan.io/address/0x916584c1a4debd37b3390b659a4a63ef7aa9f7df)
- AD Alert: https://app.forta.network/alerts/0x6961423ff4dbffb3c79719d1e75051a2c06464e8617e2b6db9953fbddfc12820
- Base bots:  [large profit bot](https://app.forta.network/bot/0x7cfeb792e705a82e984194e1e8d0e9ac3aa48ad8f6530d3017b1e2114d3519ac) and [Unusual Native Swaps Detection Bot](https://app.forta.network/bot/0xabc0bb6fe5e0d0b981dec4aa2337ce91676358c6e8bf1fec06cc558f58c3694e)
- Potential cause: large profit bot detects transactions resulting in a large profit (>$10000 or more than 5% of the token's total supply) for the initiator, to use large profit bot in AD we can customize this base bot to not alert on that txn where initiator is directly interacting with dex routers.

**Comment by Vxatz** [comment]
There is already a check implemented in the bot for Uniswap routers, but it was missing the Universal Router. We have already an open PR fixing this (and other Large Profit issues) which I'll deploy today.

**Comment by Vxatz** [comment]
(Update deployed)
