### ISSUE TITLE
Reentrancy Calls Detection Bot - FP

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#508]
Potential cause - Bot alerting for swap txs
Base bots - [Reentrancy bot](https://app.forta.network/bot/0x492c05269cbefe3a1686b999912db1fb5a39ce2e4578ac3951b0542440f435d9)

I) Attacker - [0x37913e66b277bdcd6F0768d18F623c787C5b43Cf](https://etherscan.io/address/0x37913e66b277bdcd6f0768d18f623c787c5b43cf)
 alert - https://app.forta.network/alerts/0xe1e68fcd0e8334ba80e65542a489b4e2c2bb791b5653e856a3b3c2be7f8a444c
(https://app.forta.network/bot/0x492c05269cbefe3a1686b999912db1fb5a39ce2e4578ac3951b0542440f435d9)  (uniswap)

ii)Attacker - [0x7C7C9cE081BecB5F44eF9EEd3a90d99057d2EB53](https://etherscan.io/address/0x7c7c9ce081becb5f44ef9eed3a90d99057d2eb53)
 alert - https://app.forta.network/alerts/0xbfd5ffef8bbf3e3fc7755e7939b18166e419c042cb73b7147fd03f1abcc3b8e8 (paraswap)

iii) Attacker - [0x0c723f1a99c83f6c8a6555a1dfacb7ad229c1792](https://etherscan.io/address/0x0c723f1a99c83f6c8a6555a1dfacb7ad229c1792)
 alert - https://app.forta.network/alerts/0xa17927c8bf118a14efffe2097fe0108b5bf46a67b9d1fa8faf6509e7870d4d76 (Metamask: Swap Router)

iv) https://app.forta.network/alerts/0x13fb3336a5bd25911a120d241685d40f944ad5bcd59c4fe3eec2a6c8a54c0b80 (OpenOcean: Exchange V2)

**Comment by Vxatz** [comment]
Created a PR https://github.com/NethermindEth/Forta-Agents/commit/46712290a80b162ddc21ba43c34f365c84924352

Filters out transactions with high tx count contracts called at the top-level
