### ISSUE TITLE
LARGE-PROFIT bot - FP

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#512]
Attacker - [0x453ad8d71e4767bd83a839006ea862cb05caf2e4](https://etherscan.io/address/0x453ad8d71e4767bd83a839006ea862cb05caf2e4)
Alert - https://app.forta.network/alerts/0x1b4b29845c165b5135c1fb8a7fd27df1d66efaafe0950b4ef7fc33d982e9929b 
Base bot - [Large Profit Bot](https://app.forta.network/bot/0x7cfeb792e705a82e984194e1e8d0e9ac3aa48ad8f6530d3017b1e2114d3519ac)
Seaport matchAdvancedOrders tx was flagged by the large profit bot

**Comment by Vxatz** [comment]
Filtering out Seaport in the next update.

**Comment by Vxatz** [comment]
Fix has been deployed
