### ISSUE TITLE
Funding Detector Bot - FP

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#514]
Attacker - [0x089d1f4d4021f853eed87604c254f5af44064aef](https://etherscan.io/address/0x089d1f4d4021f853eed87604c254f5af44064aef)
Base bot - [Funding Detector](https://app.forta.network/bot/0x186f424224eac9f0dc178e32d1af7be39506333783eec9463edd247dc8df8058)
Alert - https://app.forta.network/alerts/0xb241ff05b108e3cee3c1fccfa88a7a196111bd7fd524422d8a637e596745e83d
Coinbase funding tx. Maybe cexes with good kyc shouldn't be flagged by the bot?

**Comment by Ivan1905** [comment]
This one is linked to the Funding laundering bot, closing it
