### ISSUE TITLE
FN - Permit

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#517]
Hi team, 

Sharing a recent phishing the SD was not able to catch.

- [Here](https://etherscan.io/tx/0xc29220c0ef107dd93d44c922c7a2b88513df3609f54e33436d1c9bce86eb59b1) tx
- [This](https://etherscan.io/address/0xf1dd97cf70afd3d73607e08b7229bb26109ba13e) seems to be the permitted address.

**Comment by Ivan1905** [comment]
Here another one.

- [Here](https://etherscan.io/tx/0x9e711299f5b1775b266bbad2dd378a06e2a88facc3f51a2b95c73560544efa81) the tx.

- [Here](https://etherscan.io/address/0x1e9b7a54cde48d70a6fc4dac9492f85da682f975#internaltx) the permitted address

**Comment by Vxatz** [comment]
Fixed in the last SD update.
