### ISSUE TITLE
"high-gas-used-bot" Issue on L2's

### ISSUE THREAD

**Issue by 0xhowen** [forta-network/starter-kits#518]
AD alert:  [AD Combination Alert](https://app.forta.network/alerts/0x1698ee2af77e712ef3d23dd1c8a9764caca4f80a227f286e7df8e8628d4181ff)

Base bots: [high-gas-used-bot](https://app.forta.network/bot/0x3858be37e155f84e8e0d6212db1b47d4e83b1d41e8a2bebecb902651ed1125d6), [suspicious-contract-creation](https://app.forta.network/bot/0x457aa09ca38d60410c8ffa1761f535f23959195a56c9b82e0207801e86b34d99)

Potential Cause: L2 gas calculation is different from L1 gas calculation. Because the gas is hardcoded to four and six million gas, it creates an issue where L2's can have false positives due to over reported gas used. 

The alert was triggered on the alert above because it was > 4m gas. If we look closely on [arbiscan])(https://arbiscan.io/tx/0x72cd2bad8231855f42ce2ced3fdb4bedfdf71c39a0e12b884f423e5bbee43e1a), we can see under advanced txinfo that the actual L2 gas used is 2,154,554 million. 

Another example: Just a random ether [transfer](https://arbiscan.io/tx/0xa40b14df9521e17cee731ad2f8254b9a50f2c36a17227539211563a691616d2f). Shows 675,520 gas which is much higher than the 21,000 gas needed for this. However, under advanced txinfo it is 21,000 for L2 gas used.

Recommendation: Calculate L2 gas used and use this value for the threshold instead of total L1 + L2 gas.

**Comment by Thisisgeorg3** [comment]
Nice find @0xhowen thank you

**Comment by Vxatz** [comment]
Fixed in https://github.com/NethermindEth/Forta-Agents/pull/470
