### ISSUE TITLE
LARGE-TRANSFER-OUT - FP

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#528]
Alert - https://app.forta.network/alerts/0x1c462fbc35049e702965d2c0b40a8fe15e4d71db1a6611fe0d3aaa76ee1cd168
Reasons - Pancakeswap addLiquidity tx

**Comment by Vxatz** [comment]
Fixed in https://github.com/forta-network/starter-kits/pull/536
