### ISSUE TITLE
FN - private key compromise

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#539]
Hi!

Recently there was a big PCK compromise where:

- Attacker was added as a minter - [here](https://etherscan.io/tx/0xe834f28377b79759ac5495a91975a01e0876af9aae312228c1ac525846406170)
- Address minted [here](https://etherscan.io/tx/0xe8be05f6a3360f63b9e78a30b4ba16ea4c7d0b530a8abf99390f1c831851fb7e) and [here](https://etherscan.io/tx/0x5f73c86a516616e25b3d13188f3289472d22a06cb1029ff174e00596a97e13b9)

Do we know in cases of tokens that have been for a while, does addminter frecuently happens?
I'm thinking that if it's super strange to add a new minter, maybe we could add coverage. The gap here between the addminter and the mint was 6 minutes and maybe it could have been prevented

**Comment by Vxatz** [comment]
If we start seeings FPs on Attack Detector, we could later remove it

**Comment by Thisisgeorg3** [comment]
Thanks @Vxatz
