### ISSUE TITLE
ICE-PHISHING-SUSPICIOUS-TRANSFER - FP

### ISSUE THREAD

**Issue by 0xbhagi** [forta-network/starter-kits#548]
- Attacker: [0xf8ed18a91cdf4242d80c756728dbf307b98e404e](https://polygonscan.com/address/0xf8ed18a91cdf4242d80c756728dbf307b98e404e)
- AD Alert: https://app.forta.network/alerts/0xf52d3fff50cd4c4d54231068ffa8fea295bc750980e224b6fb856e524c5e52ac
- Base bots:  [Ice Phishing Detection Bot](https://app.forta.network/bot/0x8badbf2ad65abc3df5b1d9cc388e419d9255ef999fb69aac6bf395646cf01c14)
- Potential cause:  base alerts https://app.forta.network/alerts/0x752306ea166af04643b3e7a368428ba8bc4f2552dd185eaaef1fc61f49371623 pointing  0xf8ed18a91cdf4242d80c756728dbf307b98e404e at txn https://polygonscan.com/tx/0x6f501dc86ec157362aabcdfcb2b299b886bc51b84034b565d1d6f0fe22c2ee22 as  ICE-PHISHING-SUSPICIOUS-TRANSFER  which is FP, Improvements can be made to Ice Phishing Detection Bot.

**Comment by Ivan1905** [comment]
Agree this is FP and based on the analysis we made where all the phishing labels were analyzed, ICE-PHISHING-SUSPICIOUS-TRANSFER is suffering from various FPs. [A ticket](https://github.com/forta-network/starter-kits/issues/561) was opened to mitigate this one.

**Comment by Thisisgeorg3** [comment]
Thanks @Ivan1905
