### ISSUE TITLE
High Gas Use Detection - FP

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#552]
Attacker - (https://bscscan.com/address/0x215c63fc21b96424a05fce242fdca5ad97d6fd42) 
AD alert - https://app.forta.network/alerts/0x7d6457074fbd348e7cf2330a0d43683fd8f41284d68c2012f50e0353383262ee
potential cause - high gas alert triggered on [minting](https://app.forta.network/alerts/0x6dfe207f9208e26fd26de8ce90d66519b0ff0e16f837c7311945d660868d3748) gas tokens
Base bots - [suspicious-contract-creation](https://app.forta.network/bot/0x457aa09ca38d60410c8ffa1761f535f23959195a56c9b82e0207801e86b34d99), [malicious-smart-contract](https://app.forta.network/bot/0x9aaa5cd64000e8ba4fa2718a467b90055b70815d60351914cc1cbe89fe1c404c) and [high-gas](https://app.forta.network/bot/0x3858be37e155f84e8e0d6212db1b47d4e83b1d41e8a2bebecb902651ed1125d6)

Similar AD alert - https://app.forta.network/alerts/0xcc7238e6a45241584e11145276766c6aff440f672c5db149858dfc58b12cce34
https://app.forta.network/alerts/0x91016eefb72f0be2a64f454f11af21a2c7251855b8446f14aaffd71937f2a0c6

**Comment by Vxatz** [comment]
Fixed in https://github.com/NethermindEth/Forta-Agents/pull/472
