### ISSUE TITLE
LARGE-PROFIT - FP

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#554]
Attacker - [0x2a0d3b1adb0b0777f9c431dc63d29dceba9fa5d0](https://bscscan.com/address/0x2a0d3b1adb0b0777f9c431dc63d29dceba9fa5d0)
AD alert - https://app.forta.network/alerts/0x7a8d02688059690ce6baa25ef7978d93502f19b05703e28d2fa97b84b34b26f1
Base bots - [Large Profit Bot](https://app.forta.network/bot/0x7cfeb792e705a82e984194e1e8d0e9ac3aa48ad8f6530d3017b1e2114d3519ac) and [Ownership Transfer](https://app.forta.network/bot/0x7704a975c97ed444c0329cade1f85af74566d30fb6a51550529b19153a0781cb)
Potential cause. The "profit" was [sent] to the initiator (https://app.forta.network/alerts/0xf93b879d3a5914cfcca9e479ddff9cfd16fabea949426428f67ece79ed4fd953) from a contract deployed by the initiator

**Comment by Vxatz** [comment]
A profit in this transaction was incorrectly attributed to the Pancake Pair. It has been fixed since the most recent Large Profit update.

**Comment by Thisisgeorg3** [comment]
Thanks @Vxatz
