### ISSUE TITLE
ASSET-DRAINED-FP

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#555]
Attacker - [0xaaaf0666a916bdf97710a8e44e42ba250490e5b8](https://etherscan.io/address/0xaaaf0666a916bdf97710a8e44e42ba250490e5b8) 
AD alert - https://app.forta.network/alerts/0x20dc67ca5bce9f79da2be1c37925530c7e0e67b82a7df54d0020e80177ece83f
Base bots - [malicious-smart-contract](https://app.forta.network/bot/0x9aaa5cd64000e8ba4fa2718a467b90055b70815d60351914cc1cbe89fe1c404c) and [Asset Drained](https://app.forta.network/bot/0xe4a8660b5d79c0c64ac6bfd3b9871b77c98eaaa464aa555c00635e9d8b33f77f)
Potential cause - contract creator [transferred](https://app.forta.network/alerts/0x2eb170d4ea38a39b0e617aea8b61f5dae267374f8a23ea126f689bcc7283b8eb) tokens from the contract

**Comment by Vxatz** [comment]
Created https://github.com/NethermindEth/forta-starter-kits/pull/102, which excludes contract creators (in cases other than liquidity removals for which we already have a separate alert ID).

**Comment by Vxatz** [comment]
Fix has been deployed
