### ISSUE TITLE
 Large profit bot - FP

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#566]
Attacker -  [0xdcece0f25a7e7e5e4eab84ff2a8d807302eb04f1](https://etherscan.io/address/0xdcece0f25a7e7e5e4eab84ff2a8d807302eb04f1)  
AD alert - https://app.forta.network/alerts/0x7a535254559a1cdd51847f9c12a34e14b6b6ec95b740f9e233cd78fce7eed87d
Base bots - [Large Profit](https://app.forta.network/bot/0x7cfeb792e705a82e984194e1e8d0e9ac3aa48ad8f6530d3017b1e2114d3519ac) and [Large Transfer Out](https://app.forta.network/bot/0xaf9ac4c204eabdd39e9b00f91c8383dc01ef1783e010763cad05cc39e82643bb)
potential cause - [uniswap tx for an erc404 token]
(https://app.forta.network/alerts/0x7365acbf3fd85abbf15483b8227597567afc53e07e70a6a9177fde054489007a)

another example - https://app.forta.network/alerts/0xe87d362940101a3282cfad653fb4b5785992abfc2c107c4506967d4bd2786579

**Comment by Vxatz** [comment]
This has been fixed in the latest update, since which, we're expecting ERC20 Transfer events from more than one tokens (in both cases there was only WETH)
