### ISSUE TITLE
Flashloan Detection Bot-FP

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#567]
Attacker - [0x479e618e0f214100a2ea3418c4911e26ffc37795](https://optimistic.etherscan.io/address/0x479e618e0f214100a2ea3418c4911e26ffc37795)   
AD alert - https://app.forta.network/alerts/0x95beabd15c9289894c4b625a7f2a2813f1201ebff92b416ec583d5410247fe15
Base bots - [suspicious-contract-creation](https://app.forta.network/bot/0x457aa09ca38d60410c8ffa1761f535f23959195a56c9b82e0207801e86b34d99), [malicious-smart-contract](https://app.forta.network/bot/0x9aaa5cd64000e8ba4fa2718a467b90055b70815d60351914cc1cbe89fe1c404c) and [Flashloan Detection Bot](https://app.forta.network/bot/0x55636f5577694c83b84b0687eb77863850c50bd9f6072686c8463a0cbc5566e0)
potential cause - The bot [flagged](https://app.forta.network/alerts/0x4ff69f6411074efa57078cd15c1ca0a510037f9d7ed22802a29ecb7606401337) a debt liquidation tx on exactly protocol

**Comment by Vxatz** [comment]
I added a check to filter out the two liquidate functions used in this:
`liquidate(uint256)`
`liquidate(address,uint256,address)`

**Comment by Thisisgeorg3** [comment]
Should I close? @Vxatz

**Comment by Vxatz** [comment]
@Thisisgeorg3 , since we're still testing other changes to the bot, let's leave it open until it's deployed

**Comment by Vxatz** [comment]
Fixed in https://github.com/NethermindEth/forta-starter-kits/pull/96.
