### ISSUE TITLE
Native ice phishing - NIP-4 and NIP-7

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#595]
Hi there,

We have recently been working on a Binance analysis to see how scammers are interacting with the exchange. The process was basically matching scammers labeled by the scam detector with addresses that have received native tokens from binance for mainnet.

When querying those addresses we found some cases that I would like to discuss all were labeled either by the NIP-4 or NIP-7:

- [0x0e58e8993100f1cbe45376c410f97f4893d9bfcd](https://etherscan.io/address/0x0e58e8993100f1cbe45376c410f97f4893d9bfcd)
- [0x1a6a80a836b3b7dee660fbc7a5ea1ded367f2d24](https://etherscan.io/address/0x1a6a80a836b3b7dee660fbc7a5ea1ded367f2d24)
- [0xfe2ffe10ee4f87e191a7d32043296fe023ce5366](https://etherscan.io/address/0xfe2ffe10ee4f87e191a7d32043296fe023ce5366)

These all have same patterns as victims are sending ETH to not only the potential scammer but also to other addresses. IMHO (although the logic seems to be working fine) I don't believe these should be catalogued as scammers, as many txs are too big and as I mentioned these victim are sending eth to multiple addresses. Moreover, I have not seen that these were labeled by any entity or security team.
To conclude, just an observation, these are hard to analyze considering the only thing that I can see is a transfer, impossible to know if these were scam transfers or normal ones (seems like a similar case to PKC). What could we do here? should we think of dismiss native transfer, should we tweak the bot?

**Comment by Vxatz** [comment]
After discussing, we have removed NIP-4 and NIP-7 passthrough alerts from the Scam Detector.
