### ISSUE TITLE
Asset-Drained - FP

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#607]
Attacker -[0x947b05e9ac793ad8acb326f965b9641529b818b6](https://etherscan.io/address/0x947b05e9ac793ad8acb326f965b9641529b818b6)   
Base bots - [malicious-smart-contract](https://app.forta.network/bot/0x9aaa5cd64000e8ba4fa2718a467b90055b70815d60351914cc1cbe89fe1c404c), [suspicious-contract-creation](https://app.forta.network/bot/0x457aa09ca38d60410c8ffa1761f535f23959195a56c9b82e0207801e86b34d99) and [Asset Drained](https://app.forta.network/bot/0xe4a8660b5d79c0c64ac6bfd3b9871b77c98eaaa464aa555c00635e9d8b33f77f)
AD alert - https://app.forta.network/alerts/0xe450f3055c1249685a12ecc31926728139edd92055341081d44dfa7f717ba934
Potential cause - [withdrawal](https://etherscan.io/tx/0x31e1a4341d6ed8c6d60a5fcbe6eac77b61fd2b116ea4cefea943ce9d505f466c) from gnosis Safe Smart Account

**Comment by Vxatz** [comment]
Fixed in https://github.com/NethermindEth/forta-starter-kits/pull/106.
