### ISSUE TITLE
FP for malicious-contract v3

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#610]
Attacker - https://snowtrace.io/address/0x55faa8f9b8c5faba0444eec366cecfd78b7449b6
AD alert - https://app.forta.network/alerts/0xcf83624444748243f9c4c7c758a4a755d5da7b375533fca6f4f4de4bef86d326
Base bots - [malicious-smart-contract](https://app.forta.network/bot/0x9aaa5cd64000e8ba4fa2718a467b90055b70815d60351914cc1cbe89fe1c404c) and [ChangeNow Funding](https://app.forta.network/bot/0x9324d7865e1bcb933c19825be8482e995af75c9aeab7547631db4d2cd3522e0e)
potential cause - Failed [contract creation tx](https://app.forta.network/alerts/0x63247a72ad80f3d8140871725d9f052891154f298a91f3c4110965b1adc2da2e)

**Comment by Thisisgeorg3** [comment]
@salort-forta can you please check if the issue here is to model logic?

**Comment by salort-forta** [comment]
The prediction is over the threshold, and there is funding. I think the problem is that ChangeNw funding is not inherently malicious, but we still don't have a way of grading that that is not binary
