### ISSUE TITLE
Large Profit - FP

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#611]
Attacker -  [0xb616aab729a17d325fe221ad7875ae6a9caefc12](https://etherscan.io/address/0xb616aab729a17d325fe221ad7875ae6a9caefc12) 
AD alert - https://app.forta.network/alerts/0x3f63acb23fc2feaa8a627458e09285634f5e52dbdff13f14a6214d4850e8fd7c
Base bots - [Unusual Native Swaps](https://app.forta.network/alerts/0x3f63acb23fc2feaa8a627458e09285634f5e52dbdff13f14a6214d4850e8fd7c) and [Large Profit Bot](https://app.forta.network/bot/0x7cfeb792e705a82e984194e1e8d0e9ac3aa48ad8f6530d3017b1e2114d3519ac)
Potential cause - No profit was made by tx initiator(going by the prices [here](https://phalcon.blocksec.com/explorer/tx/eth/0x7d52853f34dbf9eb1ec843dc23524c1e4dbb3d989fa6090abbe7fb4e052a7a64) and [here](https://phalcon.blocksec.com/explorer/tx/eth/0x030827e6821a15dee2f8fc0be921d862d23d6cdb649d04860c6ab85f67e107bb)
These are the large profit alerts
https://app.forta.network/alerts/0xe978460656db3f5bf92a2d59a10831f4ae376fde476dff57766827552ea6e3b1
https://app.forta.network/alerts/0x06272b33b5402115b50fc8cec3d0fdd1e2e7203dd67b42b59c9468d013b599bb

**Comment by Vxatz** [comment]
SHIDO token was migrated at around that time to the new contract.

I believe the FP happened because a stale price was fetched, which wasn't 0 at the time (otherwise it would have been filtered out), but still low enough to consider that there was a profit in ETH after the swap
