### ISSUE TITLE
FN - drainers

### ISSUE THREAD

**Issue by Ivan1905** [forta-network/starter-kits#616]
Hi there,

Sharing some FNs coming from the ice phishing bot. Specifically cases that received allowance off-chain and then are creating the address once the permit happens.

1. This case: https://etherscan.io/tx/0xe61d0d176983fb466cf66825ca6b129642eb37fa4c43df3e72857fdd623ca4ea - There seem to be alerts from the ice phishing bot but not from the SD - https://app.forta.network/alerts?limit=15&sort=desc&text=0xea0d25e2162bf4a210c8dcfa79c3d6932d8aa8b2
2. This case: https://etherscan.io/tx/0xc29220c0ef107dd93d44c922c7a2b88513df3609f54e33436d1c9bce86eb59b1 - no alerts from the ice phishing bot: https://app.forta.network/alerts?limit=15&sort=desc&text=0xf1dd97cf70afd3d73607e08b7229bb26109ba13e
3. This other case: https://etherscan.io/tx/0xe7ec233f44dae93b59060ebd1fb1dda02dd2f67a7ae9bb315e020239b2620cfd - again, I don't see alert coming from the bot

**Comment by Ivan1905** [comment]
I remember about a month ago this was raised and fix. Maybe these last fixes are already been covered

**Comment by Vxatz** [comment]
That's right, those have been fixed in the last update (the prod version was updated on March 8). (Note that there was a phishing alert for the 2nd tx https://app.forta.network/alerts/0x57ac10b34ec064a68949f1d6c5722cb7f36af735f6f0feab886403b8216661cf)

**Comment by Ivan1905** [comment]
Thanks Vasilis, let's close this one and see how this performs in the next measurement
