### ISSUE TITLE
Malicious contract v3 -FP

### ISSUE THREAD

**Issue by Olugbenga2000** [forta-network/starter-kits#633]
Attacker - [0xfc044b822365321f6d2761b28829e3f1fda982d2](https://etherscan.io/address/0xfc044b822365321f6d2761b28829e3f1fda982d2)
Alert - https://app.forta.network/alerts/0xeac86463280d36193325d0d880852076875f735cfaaa4016c8677d3756f02a99
Base bots - [malicious-smart-contract](https://app.forta.network/bot/0x9aaa5cd64000e8ba4fa2718a467b90055b70815d60351914cc1cbe89fe1c404c), [suspicious-contract-creation](https://app.forta.network/bot/0x457aa09ca38d60410c8ffa1761f535f23959195a56c9b82e0207801e86b34d99) and [ChangeNow Funding](https://app.forta.network/bot/0x9324d7865e1bcb933c19825be8482e995af75c9aeab7547631db4d2cd3522e0e)
potential cause - non-malicious contract was [flagged](https://app.forta.network/alerts/0x3f8aa10fe4d7e0b6d63743a36aefc290e5c8502176774ceda99dc23a7f81c590)

**Comment by Ivan1905** [comment]
I would also dismiss this one considering the model will be fed according to the alerts measured
