### ISSUE TITLE
Investigate why unverified and suspicious contract creation didnt trigger on ANKR hack

### ISSUE THREAD

**Issue by christian-forta** [forta-network/starter-kits#86]
https://bscscan.com/tx/0xcbc5ff4a6c9a66274f9bde424777c3dc862ab576e282fbea3c9c2609ca3e282b

**Comment by christian-forta** [comment]
Artem, would you be able to change these as you are already changing the related code for the token impersonation one?

**Comment by kovart** [comment]
@christian-forta Sure, working on that (collecting and preparing chains data)

**Comment by 0xtaf** [comment]
both unverified contract bot and suspicious contract creation bot are able to catch it now. the related txn is https://bscscan.com/tx/0xb2cb9e5311610c48aeed89e44549542362692808257f706accdc75f051ac7303

![image](https://github.com/forta-network/starter-kits/assets/25147738/a2a58141-9d91-405b-9fb8-82ed5812c876)

![image](https://github.com/forta-network/starter-kits/assets/25147738/a66e0283-46b5-4f6d-8756-8628844b0ef7)

especi
