### ISSUE TITLE
Entity Clustering bot didn't trigger on unidirectional and bidirectional funding

### ISSUE THREAD

**Issue by kovart** [forta-network/starter-kits#95]
The bot did not trigger on an attack involving two accounts, both newly-created. 
After the attack was completed, the second account returned the remaining funds to the first account.

Accounts:
https://etherscan.io/address/0x71fcbb262a622b9ec964cc8787eb026e533f424b
https://etherscan.io/address/0xd4e10ce89c944771fb1ff173bf3b6557c692ef0d

**Comment by christian-forta** [comment]
@Ivan1905 same with this one

**Comment by christian-forta** [comment]
Likely perf issue; Nicolas refactored. Closing for now.
