### ISSUE TITLE
Protocol Anomaly Forta Detection Bot

### ISSUE THREAD

**Issue by mopdo** [forta-network/starter-kits#96]
### Prize amount
**2000USD in $FORT**

### Challenge Description
The completed Forta Detection Bot should learn the execution profile of a contract (what functions are invoked and parameter ranges) and alert on deviations from normal behavior (could also utilize execution trace to make that assessment).

The Bot should alert on transactions that appear anomalous in historical context of the contract involved. This should include transactions that invoke a contract directly or indirectly. The historical context should be built up based on 1 week (configurable) transaction history on that contract. The bot should output an anomaly score normalized to values ranging from 0.0-1.0.

Below are the types of attacks the Detection Bot should detect:
[Binance Bridge Attack](https://docs.google.com/document/d/11LkWATAUCXeXGrWoZF7o7ZJOs-3oh5NIBWzbna8r14Y/edit#heading=h.mad3g6xe3vsk) 
[PeakDeFi Hack](https://docs.google.com/document/d/1BlLP_JCC9LQ1Ns66pUQyUwTueh1_RCL0DTKWlJDfqfY/edit?usp=sharing) 
[uToken Hack](https://docs.google.com/document/d/1MgBbMvOhYTXRp7IlOr-o8b16NQDYKu2wMvG7xlK6sUA/edit?usp=sharing)

[Forta](https://forta.org/) is a real-time detection network for security & operational monitoring of blockchain activity secured by FORT token. Billions of dollars in Web3 monitored by Forta. Underlying Forta is a decentralized network of independent node operators that scan all transactions and block-by-block state changes for outlier transactions and threats. When an issue is detected, node operators send alerts to subscribers of potential risks, which enables them to take action.

[Forta Detection Bots](https://docs.forta.network/en/latest/getting-started/) are a set of code scripts within a Docker container that process some blockchain data (i.e. a block or transaction) and detect specific threat conditions (e.g. whether a flash loan attack occurred, or whether a particular account balance fell below some threshold). Bots emit alerts for their findings. Bots are executed by scan nodes.

The Forta Foundation team will review the final results and assign the rewards accordingly. Prize is paid in FORT.

The Forta Foundation will cover initial Bot deployment costs (including staking).

In order to ensure that all the work funded by the Forta Foundation under the Threat Research Initiative is made available for the benefit of Forta users, ownership over any bot that receives rewards will be assigned to the Foundation, which will be made available to the public under the "Forta Bot License ''.

Participants should also commit to making suggested improvements during the first 2 months after deployment.

### Submission Requirements
Is that it is not a requirement to have experience with blockchain development to start building on Forta.

Your web2 development experience transfers directly to Detection Bot development. In Forta, Detection Bots are programs running on the Forta Network that scan the blockchain for events of interest and alerts users about them e.g. large token transfers or declining account balances.

If you are interested in developing the Protocol Anomaly Forta Detection Bot, you can apply (sharing your Github and Linkedin accounts) for Forta to review your application before you start working on it.

**A valid submission includes:**

- a link and access to the Github repository of the Forta Detection Bot code
- a link to the deployed and staked bot, as well as being able to identify the three attacks mentioned in this bounty
- the unit test, 
- the related docs

The Detection Bot should be open source and raise less than 1000 alerts/ month based on the anomaly detection threshold defined.

### Resources
While detection bots can be written in any language, Forta provides convenient SDKs in Javascript, Typescript and Python for you to get started easily.

Detection Bots are the heart of the Forta Network as they alert users of any suspicious or anomalous activity; there are currently many Detection Bots deployed for users to interact and integrate with.

Learn more about how to develop and deploy your own Detection Bot >[ https://docs.forta.network/en/latest/getting-started/](https://docs.forta.network/en/latest/getting-started/).

**Comment by Sixto5** [comment]
Hey, hope you are well!

Thank you for sharing this project!

I'm reaching out to share our invitation to support your bounty on Gitcoin.

On our OpenQ marketplace, you will be supported fully, we are permissionless and free, see more here: [https://www.openq.dev/](https://www.openq.dev/)

Zero hassle from your side 🙂 We will mirror your bounty, adding the same budget. We have an active Developer Guild with 200 devs - from our community- that might solve your issue. So then we can create value for you meanwhile our marketplace grows.

If you give me your thumbs up we will do it and share the link again here to you for full transparency!
